force-app/main/default/objects/Procedure__c/Procedure__c.object-meta.xml
<CustomObject>
    <label>Procedure</label>
    <nameField>
        <label>Procedure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procedure</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Procedure__c/fields/AdminFieldsJson__c.field-meta.xml
<CustomField>
    <fullName>AdminFieldsJson__c</fullName>
    <label>Admin Fields JSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Procedure__c/fields/DefaultNextProcedure__c.field-meta.xml
<CustomField>
    <fullName>DefaultNextProcedure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Default Next Procedure</label>
    <referenceTo>Procedure__c</referenceTo>
    <relationshipLabel>Procedure</relationshipLabel>
    <relationshipName>Procedure</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Procedure__c/fields/IsMachineInfoRequired__c.field-meta.xml
<CustomField>
    <fullName>IsMachineInfoRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Machine Information Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Procedure__c/fields/MachineSkills__c.field-meta.xml
<CustomField>
    <fullName>MachineSkills__c</fullName>
    <label>Machine Skills</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Asset_Skill</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Procedure__c/fields/ProductionFieldsJson__c.field-meta.xml
<CustomField>
    <fullName>ProductionFieldsJson__c</fullName>
    <label>Production Fields JSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/globalValueSets/Asset_Skill.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Print</fullName>
    </customValue>
    <customValue>
        <fullName>Thru-Cut</fullName>
    </customValue>
    <customValue>
        <fullName>Kiss-Cut</fullName>
    </customValue>
    <customValue>
        <fullName>Perf-Cut</fullName>
    </customValue>
    <customValue>
        <fullName>V-Cut</fullName>
    </customValue>
    <customValue>
        <fullName>Score</fullName>
    </customValue>
    <customValue>
        <fullName>Crease</fullName>
    </customValue>
    <customValue>
        <fullName>Laminate</fullName>
    </customValue>
    <customValue>
        <fullName>Mount</fullName>
    </customValue>
    <customValue>
        <fullName>Engrave</fullName>
    </customValue>
    <customValue>
        <fullName>Staple</fullName>
    </customValue>
    <customValue>
        <fullName>Sew</fullName>
    </customValue>
    <customValue>
        <fullName>Polish</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Asset Skill</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Procedure.cls
/**
 * Wraps infromation about a procedure record.
 * @author Fernando Gomez
 * @version 1.0
 * @sicne 4/28/2024
 */
public with sharing class Procedure {
	@AuraEnabled
	public String value { get; private set; }

	@AuraEnabled
	public String label { get; private set; }

	@AuraEnabled
	public String colorCode { get; private set; }
	
	@AuraEnabled
	public String defaultNextId { get; private set; }
	
	@AuraEnabled
	public Boolean isMachineInfoRequired { get; private set; }

	@AuraEnabled
	public List<String> machineSkills { get; private set; }
	
	@AuraEnabled
	public List<ProcedureFieldInfo> adminFields { get; private set; }

	@AuraEnabled
	public List<ProcedureFieldInfo> productionFields { get; private set; }

	private Procedure(Procedure__c record) {
		value = record.Id;
		label = record.Name;
		colorCode = record.ColorCssCode__c ?? '#ffffff';
		defaultNextId = record.DefaultNextProcedure__c;
		isMachineInfoRequired = record.IsMachineInfoRequired__c;
		machineSkills =
			String.isNotBlank(record.MachineSkills__c) ?
			record.MachineSkills__c.split(';') :
			new List<String>();

		try {
			adminFields = (List<ProcedureFieldInfo>)JSON.deserialize(
				record.AdminFieldsJson__c ?? '[]', List<ProcedureFieldInfo>.class);
		} catch (Exception ex) {
			// we dn't want to block the program if it fails
			adminFields = new List<ProcedureFieldInfo>();
		}

		try {
			productionFields = (List<ProcedureFieldInfo>)JSON.deserialize(
				record.ProductionFieldsJson__c ?? '[]',
				List<ProcedureFieldInfo>.class);
		} catch (Exception ex) {
			// we dn't want to block the program if it fails
			productionFields = new List<ProcedureFieldInfo>();
		}
			
	}

	/**
	 * Returns the first 2000 procedures in the DB.
	 * @return List<Procedure>
	 */
	@AuraEnabled(cacheable=true)
	public static List<Id> getAll() {
		List<Id> result;
		try {
			result = new List<Id>();
			for (Procedure__c p : [
					SELECT Id
					FROM Procedure__c
					ORDER BY Name
					LIMIT 2000
				])
				result.add(p.Id);

			return result;
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
	}
}