force-app/main/default/objects/Staff__c/Staff__c.object-meta.xml
<CustomObject>
    <label>Staff</label>
    <nameField>
        <displayFormat>STF{00000}</displayFormat>
        <label>Staff #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staffs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Staff__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>First Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staff__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Staff__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>Last Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StaffManager.cls
/**
 * Controls: WorkOrderListView (LWC)
 * @author Fernando Gomez
 * @version 1.0
 * @since 4/9/2025
 */
public with sharing class StaffManager {

	private static final String PREVIEW_URL =
		'/sfc/servlet.shepherd/version/renditionDownload' +
		'?rendition=ORIGINAL_Png&versionId={0}&operationContext=CHATTER';

	public StaffManager() {

	}

	/**
	 * Returns info about the staff member if PIN matches.
	 * Null is returned if PIN is incorrect, employee is not active, etc.
	 * @param staffId
	 * @param pin
	 */
	@AuraEnabled
	public static Staff staffLogin(
		Id staffId,
		String pin
	) {
		List<Staff__c> staffQueryResult;
		List<ContentDocumentLink> docLinks;
		Staff__c staffRecord;
		ContentVersion profilePic;
		String photoUrl;

		try {
			staffQueryResult = [
				SELECT FirstName__c,
					LastName__c,
					FullName__c,
					PositionName__c,
					PIN__c
				FROM Staff__c
				WHERE Id = :staffId
				AND IsActive__c = true
				LIMIT 1
			];

			if (staffQueryResult.isEmpty())
				return null;

			// staff found with proper PIN
			staffRecord = staffQueryResult[0];

			// if pin is incorrect, we return null
			if (staffRecord.PIN__c != pin)
				return null;

			// we find the photo file, if any
			docLinks = [
				SELECT ContentDocument.LatestPublishedVersionId
				FROM ContentDocumentLink
				WHERE LinkedEntityId = :staffRecord.Id
				AND ContentDocument.LatestPublishedVersion.ProfilePhoto__c = true
				LIMIT 1
			];
			
			if (!docLinks.isEmpty()) {
				photoUrl = String.format(
					PREVIEW_URL,
					new List<String> {
						docLinks[0].ContentDocument.LatestPublishedVersionId
					});
			}

			return new Staff(staffRecord, photoUrl);
		} catch (Exception ex) {
			throw new AuraHandledException(ex.getMessage());
		}
	}

	public class Staff {
		@AuraEnabled
		public String firstName;

		@AuraEnabled
		public String lastName;

		@AuraEnabled
		public String fullName;

		@AuraEnabled
		public String position;

		@AuraEnabled
		public String photoUrl;

		/**
		 * staffRecord
		 * photoUrl
		 */
		public Staff(Staff__c staffRecord, String photoUrl) {
			firstName = staffRecord.FirstName__c;
			lastName = staffRecord.LastName__c;
			fullName = staffRecord.FullName__c;
			position = staffRecord.PositionName__c;
			this.photoUrl = photoUrl;
		}
	}
}