force-app/main/default/objects/DeliveryGroup__c/DeliveryGroup__c.object-meta.xml
<CustomObject>
    <label>Delivery Group</label>
    <nameField>
        <label>Delivery Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryGroup__c/fields/AddressLabel__c.field-meta.xml
<CustomField>
    <fullName>AddressLabel__c</fullName>
    <formula>IF (
  ISPICKVAL( DeliveryLocationType__c, &apos;Delivery Center&apos; ),
  DeliveryCenter__r.ShippingStreet &amp;
  IF (
    NOT(ISBLANK( DeliveryCenter__r.ShippingCity )),
    &apos;, &apos; &amp; DeliveryCenter__r.ShippingCity,
    &apos;&apos;
  )&amp;
  IF (
    NOT(ISBLANK(DeliveryCenter__r.ShippingState )),
    &apos; &apos; &amp; DeliveryCenter__r.ShippingState,
    &apos;&apos;
  ) &amp;
  IF (
    NOT(ISBLANK( DeliveryCenter__r.ShippingPostalCode )),
    &apos;, &apos; &amp; DeliveryCenter__r.ShippingPostalCode,
    &apos;&apos;
  ),
  DeliveryAddress__Street__s &amp;
  IF (
    NOT(ISBLANK( DeliveryAddress__City__s )),
    &apos;, &apos; &amp; DeliveryAddress__City__s,
    &apos;&apos;
  ) &amp;
  IF (
    NOT(ISBLANK(TEXT(DeliveryAddress__StateCode__s ))),
    &apos; &apos; &amp; TEXT(DeliveryAddress__StateCode__s),
    &apos;&apos;
  ) &amp;
  IF (
    NOT(ISBLANK( DeliveryAddress__PostalCode__s )),
    &apos;, &apos; &amp; DeliveryAddress__PostalCode__s,
    &apos;&apos;
  )
)</formula>
    <label>Address Label</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/DeliveryAddressHtml__c.field-meta.xml
<CustomField>
    <fullName>DeliveryAddressHtml__c</fullName>
    <formula>IF (
  ISPICKVAL( DeliveryLocationType__c, &apos;Delivery Center&apos; ),
  DeliveryCenter__r.ShippingStreet &amp; " " &amp;
  DeliveryCenter__r.ShippingCity &amp; &apos; &apos; &amp;
  DeliveryCenter__r.ShippingState &amp;
  IF (
    NOT(ISBLANK( DeliveryCenter__r.ShippingPostalCode )),
    &apos;, &apos; &amp; DeliveryCenter__r.ShippingPostalCode,
    &apos;&apos;
  ) &amp; " " &amp;
  DeliveryCenter__r.ShippingCountry,
  DeliveryAddress__Street__s &amp; " " &amp;
  DeliveryAddress__City__s &amp; &apos; &apos; &amp;
  TEXT(DeliveryAddress__StateCode__s) &amp;
  IF (
    NOT(ISBLANK( DeliveryAddress__PostalCode__s )),
    &apos;, &apos; &amp; DeliveryAddress__PostalCode__s,
    &apos;&apos;
  ) &amp; " " &amp;
  TEXT(DeliveryAddress__CountryCode__s)
)</formula>
    <label>Delivery Address HTML</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/DeliveryCenterName__c.field-meta.xml
<CustomField>
    <fullName>DeliveryCenterName__c</fullName>
    <formula>IF(
  ISPICKVAL(LocationType__c, &apos;Delivery Center&apos;),
  DeliveryCenter__r.Name,
  &apos;&apos;
)</formula>
    <label>Delivery Center Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/DeliveryType__c.field-meta.xml
<CustomField>
    <fullName>DeliveryType__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DeliveryType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Delivery Groups</relationshipLabel>
    <relationshipName>DeliveryGroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/recordTypes/Order.recordType-meta.xml
<RecordType>
    <fullName>Order</fullName>
    <active>true</active>
    <label>Order</label>
</RecordType>

force-app/main/default/objects/PackingSlip__c/PackingSlip__c.object-meta.xml
<CustomObject>
    <label>Packing Slip</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Packing Slip #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packing Slips</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PackingSlip__c/fields/DeliveryGroup__c.field-meta.xml
<CustomField>
    <fullName>DeliveryGroup__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Delivery Group</label>
    <referenceTo>DeliveryGroup__c</referenceTo>
    <relationshipLabel>Packing Slips</relationshipLabel>
    <relationshipName>PackingSlips</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PackingSlip__c/fields/DeliveryType__c.field-meta.xml
<CustomField>
    <fullName>DeliveryType__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Delivery_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PackingSlip__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Packing Slips</relationshipLabel>
    <relationshipName>PackingSlips</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PackingSlipItem__c/PackingSlipItem__c.object-meta.xml
<CustomObject>
    <label>Packing Slip Item</label>
    <nameField>
        <displayFormat>PSI{000000}</displayFormat>
        <label>Packing Slip Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packing Slip Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PackingSlipItem__c/fields/PackingSlip__c.field-meta.xml
<CustomField>
    <fullName>PackingSlip__c</fullName>
    <label>Packing Slip</label>
    <referenceTo>PackingSlip__c</referenceTo>
    <relationshipLabel>Packing Slip Items</relationshipLabel>
    <relationshipName>PackingSlipItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PackingSlipTemplateOverride__c/PackingSlipTemplateOverride__c.object-meta.xml
<CustomObject>
	<label>Packing Slip Template</label>
	<nameField>
		<label>Packing Slip Template Name</label>
		<type>Text</type>
	</nameField>
	<pluralLabel>Packing Slip Templates</pluralLabel>
	<sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PackingSlipTemplateOverride__c/fields/Body__c.field-meta.xml
<CustomField>
	<fullName>Body__c</fullName>
	<label>Body</label>
	<length>32768</length>
	<type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PackingSlipTemplateOverride__c/fields/Description__c.field-meta.xml
<CustomField>
	<fullName>Description__c</fullName>
	<label>Description</label>
	<length>255</length>
	<type>Text</type>
</CustomField>

force-app/main/default/objects/PackingSlipTemplateOverride__c/fields/Dimensions__c.field-meta.xml
<CustomField>
	<fullName>Dimensions__c</fullName>
	<label>Dimensions</label>
	<required>true</required>
	<type>Picklist</type>
	<valueSet>
		<restricted>true</restricted>
		<valueSetDefinition>
			<value><fullName>LABEL_6X4</fullName><default>false</default><label>6&quot; x 4&quot;</label></value>
			<value><fullName>LETTER_8_5X11</fullName><default>true</default><label>8.5&quot; x 11&quot;</label></value>
		</valueSetDefinition>
	</valueSet>
</CustomField>

force-app/main/default/objects/PackingSlipTemplateOverride__c/fields/Is_Active__c.field-meta.xml
<CustomField>
	<fullName>Is_Active__c</fullName>
	<defaultValue>false</defaultValue>
	<label>Is Active</label>
	<type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PackingSlipTemplateOverride__c/fields/Output_Mode__c.field-meta.xml
<CustomField>
	<fullName>Output_Mode__c</fullName>
	<label>Output Mode</label>
	<required>true</required>
	<type>Picklist</type>
	<valueSet>
		<restricted>true</restricted>
		<valueSetDefinition>
			<value><fullName>SCREEN</fullName><default>true</default><label>Screen</label></value>
			<value><fullName>PRINT</fullName><default>false</default><label>Print</label></value>
		</valueSetDefinition>
	</valueSet>
</CustomField>

force-app/main/default/objects/PackingSlipTemplateOverride__c/fields/Provider_Key__c.field-meta.xml
<CustomField>
	<fullName>Provider_Key__c</fullName>
	<label>Provider Key</label>
	<length>80</length>
	<required>true</required>
	<type>Text</type>
</CustomField>

force-app/main/default/objects/PackingSlipTemplateOverride__c/fields/Subscriber_Override__c.field-meta.xml
<CustomField>
	<fullName>Subscriber_Override__c</fullName>
	<defaultValue>true</defaultValue>
	<label>Subscriber Override</label>
	<type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PackingSlipTemplateOverride__c/fields/Template_Key__c.field-meta.xml
<CustomField>
	<fullName>Template_Key__c</fullName>
	<label>Template Key</label>
	<length>80</length>
	<required>true</required>
	<type>Text</type>
</CustomField>

force-app/main/default/objects/PackingSlipTemplateOverride__c/fields/Template_Type__c.field-meta.xml
<CustomField>
	<fullName>Template_Type__c</fullName>
	<label>Template Type</label>
	<required>true</required>
	<type>Picklist</type>
	<valueSet>
		<restricted>true</restricted>
		<valueSetDefinition>
			<value><fullName>HTML</fullName><default>true</default><label>HTML</label></value>
			<value><fullName>PDF</fullName><default>false</default><label>PDF</label></value>
			<value><fullName>ZPL</fullName><default>false</default><label>ZPL</label></value>
		</valueSetDefinition>
	</valueSet>
</CustomField>

force-app/main/default/globalValueSets/DeliveryType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Delivery</fullName>
        <default>true</default>
        <label>Delivery</label>
    </customValue>
    <customValue>
        <fullName>Installation</fullName>
    </customValue>
    <customValue>
        <fullName>FedEx</fullName>
    </customValue>
    <customValue>
        <fullName>UPS</fullName>
    </customValue>
    <customValue>
        <fullName>DHL</fullName>
    </customValue>
    <customValue>
        <fullName>Courier</fullName>
    </customValue>
    <customValue>
        <fullName>Uber</fullName>
    </customValue>
    <customValue>
        <fullName>Pick Up</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Delivery Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PackingSlipControllerTest.cls
@IsTest
private class PackingSlipControllerTest {
	private static Id buildFakePackingSlipId() {
		return Id.valueOf(PackingSlip__c.SObjectType.getDescribe().getKeyPrefix() + '000000000000AAA');
	}

	private static void primeProviderTestData(Id packingSlipId) {
		PackingSlip__c packingSlip = new PackingSlip__c(
			TrackingNumber__c = 'TRK-400',
			Description__c = 'Controller test'
		);
		packingSlip.put('Name', 'PS-400');

		Order orderRecord = new Order();
		orderRecord.put('OrderNumber', 'ORD-400');
		packingSlip.putSObject('Order__r', orderRecord);

		SObject deliveryGroupRecord = Schema.getGlobalDescribe().get('DeliveryGroup__c').newSObject();
		deliveryGroupRecord.put('Name', 'Katherine Johnson');
		deliveryGroupRecord.put('DeliveryCenterName__c', 'Katherine Johnson');
		deliveryGroupRecord.put('AddressLabel__c', 'Katherine Johnson');
		deliveryGroupRecord.put('DeliveryAddressHtml__c', '1 Orbit Way');
		deliveryGroupRecord.put('DeliveryType__c', 'Ground');
		packingSlip.putSObject('DeliveryGroup__r', deliveryGroupRecord);

		DefaultPackingSlipDataProvider.setTestData(
			packingSlipId,
			packingSlip,
			new List<PackingSlipItem__c>()
		);
	}

	@IsTest
	static void controller_methods_returnRenderDataAndCloneDefaults() {
		Id packingSlipId = buildFakePackingSlipId();
		primeProviderTestData(packingSlipId);

		PackingSlipDataModels.TemplateDefinition screenTemplate = new PackingSlipDataModels.TemplateDefinition();
		screenTemplate.templateKey = 'DefaultHtml';
		screenTemplate.dimensions = 'LETTER_8_5X11';
		screenTemplate.name = 'Screen';
		screenTemplate.templateType = 'HTML';
		screenTemplate.outputMode = 'SCREEN';
		screenTemplate.providerKey = 'SHIPMENT';
		screenTemplate.isActive = true;
		screenTemplate.source = 'PACKAGED';
		screenTemplate.body = '<div>{{OrderNumber}}</div>';

		PackingSlipTemplateRepository.setTestData(
			new List<PackingSlipDataModels.TemplateDefinition>(),
			new List<PackingSlipDataModels.TemplateDefinition>{ screenTemplate },
			new List<PackingSlipDataModels.FieldMapDefinition>()
		);

		Test.startTest();
		PackingSlipDataModels.RenderResponse response =
			PackingSlipController.previewHtml(packingSlipId, 'DefaultHtml');
			List<PackingSlipDataModels.TemplateOption> options =
				PackingSlipController.getTemplateOptions(packingSlipId);
			String pdfUrl = PackingSlipController.getPdfUrl(packingSlipId, 'DefaultHtml', 'LABEL_6X4');
			Id clonedTemplateId = PackingSlipController.cloneDefaultTemplate('DefaultHtml');
		Test.stopTest();

		System.assert(response.html.contains('ORD-400'));
		System.assertEquals(1, options.size());
		System.assert(pdfUrl.contains('/apex/PackingSlipPdf'));
		System.assert(pdfUrl.contains('pageSize=LABEL_6X4'));
		System.assertNotEquals(null, clonedTemplateId);

		PackingSlipTemplateRepository.clearTestData();
		DefaultPackingSlipDataProvider.clearTestData();
	}

	@IsTest
	static void adminService_activatesSingleTemplatePerOutputMode() {
		PackingSlipTemplateOverride__c firstTemplate = new PackingSlipTemplateOverride__c(
			Name = 'Template A',
			Template_Key__c = 'A',
			Template_Type__c = 'HTML',
			Output_Mode__c = 'SCREEN',
			Dimensions__c = 'LETTER_8_5X11',
			Provider_Key__c = 'SHIPMENT',
			Is_Active__c = true,
			Body__c = '<div>A</div>',
			Subscriber_Override__c = true
		);
		PackingSlipTemplateOverride__c secondTemplate = new PackingSlipTemplateOverride__c(
			Name = 'Template B',
			Template_Key__c = 'B',
			Template_Type__c = 'HTML',
			Output_Mode__c = 'SCREEN',
			Dimensions__c = 'LETTER_8_5X11',
			Provider_Key__c = 'SHIPMENT',
			Is_Active__c = false,
			Body__c = '<div>B</div>',
			Subscriber_Override__c = true
		);
		insert new List<PackingSlipTemplateOverride__c>{ firstTemplate, secondTemplate };

		Test.startTest();
			PackingSlipController.setTemplateActive(secondTemplate.Id, true);
		Test.stopTest();

		Map<Id, PackingSlipTemplateOverride__c> recordsById = new Map<Id, PackingSlipTemplateOverride__c>([
			SELECT Id, Is_Active__c
			FROM PackingSlipTemplateOverride__c
			WHERE Id IN :new Set<Id>{ firstTemplate.Id, secondTemplate.Id }
		]);

		System.assertEquals(false, recordsById.get(firstTemplate.Id).Is_Active__c);
		System.assertEquals(true, recordsById.get(secondTemplate.Id).Is_Active__c);
	}
}