force-app/main/default/objects/DeliveryGroup__c/DeliveryGroup__c.object-meta.xml
<CustomObject>
    <label>Delivery Group</label>
    <nameField>
        <label>Delivery Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryGroup__c/fields/DeliveryType__c.field-meta.xml
<CustomField>
    <fullName>DeliveryType__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DeliveryType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/recordTypes/Order.recordType-meta.xml
<RecordType>
    <fullName>Order</fullName>
    <active>true</active>
    <label>Order</label>
</RecordType>

force-app/main/default/objects/OrderItem/fields/DeliveryGroup__c.field-meta.xml
<CustomField>
    <fullName>DeliveryGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Delivery Group and the Order Product must be related to the same order.</errorMessage>
        <filterItems>
            <field>$Source.OrderId</field>
            <operation>equals</operation>
            <valueField>DeliveryGroup__c.Order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DeliveryGroup__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>OrderProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DeliveryType__c.field-meta.xml
<CustomField>
    <fullName>DeliveryType__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DeliveryType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItemWorkOrder__c/OrderItemWorkOrder__c.object-meta.xml
<CustomObject>
    <label>Order Product Work Order</label>
    <nameField>
        <displayFormat>OIWO{000000}</displayFormat>
        <label>Order Item Work Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Products Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItemWorkOrder__c/fields/OrderItem__c.field-meta.xml
<CustomField>
    <fullName>OrderItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Order Products Work Orders</relationshipLabel>
    <relationshipName>OrderItemsWorkOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItemWorkOrder__c/fields/WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>WorkOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipName>OrderItemsWorkOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Finish__c.field-meta.xml
<CustomField>
    <fullName>Finish__c</fullName>
    <label>Finish</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Finishing</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductionOrder__c/ProductionOrder__c.object-meta.xml
<CustomObject>
    <label>Production Order</label>
    <nameField>
        <displayFormat>PO{00000000}</displayFormat>
        <label>Production Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Production Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductionOrder__c/fields/Depth__c.field-meta.xml
<CustomField>
    <fullName>Depth__c</fullName>
    <label>Depth</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProductionOrder__c/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Height__c</fullName>
    <label>Height</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProductionOrder__c/fields/Width__c.field-meta.xml
<CustomField>
    <fullName>Width__c</fullName>
    <label>Width</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/DeliveryType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Delivery</fullName>
        <default>true</default>
        <label>Delivery</label>
    </customValue>
    <customValue>
        <fullName>Installation</fullName>
    </customValue>
    <customValue>
        <fullName>FedEx</fullName>
    </customValue>
    <customValue>
        <fullName>UPS</fullName>
    </customValue>
    <customValue>
        <fullName>DHL</fullName>
    </customValue>
    <customValue>
        <fullName>Courier</fullName>
    </customValue>
    <customValue>
        <fullName>Uber</fullName>
    </customValue>
    <customValue>
        <fullName>Pick Up</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Delivery Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Finishing.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
        <default>true</default>
        <label>Standard</label>
    </customValue>
    <customValue>
        <fullName>Deluxe</fullName>
    </customValue>
    <customValue>
        <fullName>Matte</fullName>
    </customValue>
    <customValue>
        <fullName>Gloss</fullName>
    </customValue>
    <customValue>
        <fullName>Semi-Gloss</fullName>
    </customValue>
    <customValue>
        <fullName>Dry Erase</fullName>
    </customValue>
    <customValue>
        <fullName>Double Sided</fullName>
    </customValue>
    <customValue>
        <fullName>UV Coating</fullName>
    </customValue>
    <customValue>
        <fullName>No Coating</fullName>
    </customValue>
    <customValue>
        <fullName>Spot UV in both sides</fullName>
    </customValue>
    <customValue>
        <fullName>Spot UV on one side</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Finishing</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OrderManager.cls
/**
 * Order manager. Main functionality involving the Order object.
 * @author Fernando Gomez
 * @version 1.0 5/15/2023
 */
public with sharing class OrderManager {
	private List<Id> orderIds;
	private List<Order> orders;

	public OrderManager(Id orderId) {
		this(new List<Id> { orderId });
	}

	public OrderManager(List<Id> orderIds) {
		this.orderIds = orderIds;
		this.orders = getOrdersByIds(orderIds);
	}

	/**
	 * Returns Orders with their related OrderItems
	 * @param workOrderId The Work Order Id to query OrderItems from
	 * @return List of Orders with related OrderItems
	 */
	@AuraEnabled(cacheable=true)
	public static List<Order> getOrderAndOrderItemsByWorkOrder(Id workOrderId) {
		Set<Id> orderIds = new Set<Id>();
		Set<Id> orderItemIds = new Set<Id>();
		
		for (OrderItemWorkOrder__c woi : [
			SELECT OrderItem__r.OrderId,
				OrderItem__c 
			FROM OrderItemWorkOrder__c 
			WHERE WorkOrder__c = :workOrderId
		]) {
			orderIds.add(woi.OrderItem__r.OrderId);
			orderItemIds.add(woi.OrderItem__c);
		}
		
		return [
			SELECT Name,
				DueDate__c,
				OrderNumber,
				Status,
				TotalAmount,
				AccountId,
				Account.Name,
				(
					SELECT OrderId,
						OrderItemNumber,
						AvailableQuantity,
						BasePrice__c,
						CreatedDate,
						DeliveryGroup__c,
						DeliveryType__c,
						Width__c,
						Height__c,
						Depth__c,
						Description,
						EndDate,
						ListPrice,
						Notes__c,
						PricebookEntryId,
						Product2Id,
						Product2.Name,
						Product2.ProductCode,
						Product2.Finish__c,
						Quantity,
						TotalPrice,
						UnitPrice,
						UnitType__c
					FROM OrderItems
					WHERE Id = :orderItemIds
				)
			FROM Order
			WHERE Id IN :orderIds
		];
	}

	/**
	 * Creates Work Orders based on the Order Products
	 * in the current Orders.
	 */
	public void createProductionOrders() {
		String uniqueKey;
		String uniqueKeyPattern = '{0}:{1}:{2}x{3}x{4}';
		Map<String, List<OrderItem>> itemsMappedByProduct;
		List<ProductionOrder__c> productionOrders = new List<ProductionOrder__c>();

		for (Order o : orders) {
			// all items of t he same product with the same width, height, and depth
			itemsMappedByProduct = new Map<String, List<OrderItem>>();

			// we group the items based on unique key...
			// same product + unit type + meassurements
			for (OrderItem oi : o.OrderItems) {
				uniqueKey = String.format(
					uniqueKeyPattern,
					new List<String> {
						oi.Product2Id,
						oi.UnitType__c,
						String.valueOf(oi.Width__c),
						String.valueOf(oi.Height__c),
						String.valueOf(oi.Depth__c)
					});

				if (itemsMappedByProduct.containsKey(uniqueKey))
					itemsMappedByProduct.get(uniqueKey).add(oi);
				else
					itemsMappedByProduct.put(
						uniqueKey,
						new List<OrderItem> { oi });
			}

			// now we have the group, we'll create
			// a work order per group
			/* for (String key : itemsMappedByProduct.keySet())
				productionOrders.add(new ProductionOrder__c(

				)); */
		}
	}

	/* public OrderManager(List<Order> orders) {
		this.orders = orders;
	} */

	private List<Order> getOrdersByIds(List<Id> orderIds) {
		return [
			SELECT Name,
				AccountId,
				(
					SELECT OrderItemNumber,
						AvailableQuantity,
						BasePrice__c,
						CreatedDate,
						DeliveryGroup__c,
						DeliveryType__c,
						Width__c,
						Height__c,
						Depth__c,
						Description,
						EndDate,
						ListPrice,
						Notes__c,
						OrderId,
						PricebookEntryId,
						Product2Id,
						Product2.Name,
						Product2.ProductCode,
						Product2.Finish__c,
						Quantity,
						TotalPrice,
						UnitPrice,
						UnitType__c
					FROM OrderItems
				)
			FROM Order
			WHERE Id IN :orderIds
		];
	}
}