force-app/main/default/objects/DeliveryGroup__c/DeliveryGroup__c.object-meta.xml
<CustomObject>
    <label>Delivery Group</label>
    <nameField>
        <label>Delivery Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryGroup__c/fields/AddressHtml__c.field-meta.xml
<CustomField>
    <fullName>AddressHtml__c</fullName>
    <formula>IF (
  ISPICKVAL( LocationType__c, &apos;Venue&apos; ),
  DeliveryCenter__r.ShippingStreet &amp; BR() &amp;
  DeliveryCenter__r.ShippingCity &amp; &apos; &apos; &amp;
  DeliveryCenter__r.ShippingState &amp;
  IF (
    NOT(ISBLANK( DeliveryCenter__r.ShippingPostalCode )),
    &apos;, &apos; &amp; DeliveryCenter__r.ShippingPostalCode,
    &apos;&apos;
  ) &amp; BR() &amp;
  DeliveryCenter__r.ShippingCountry,
  Address__Street__s &amp; BR() &amp;
  Address__City__s &amp; &apos; &apos; &amp;
  TEXT(Address__StateCode__s) &amp;
  IF (
    NOT(ISBLANK( Address__PostalCode__s )),
    &apos;, &apos; &amp; Address__PostalCode__s,
    &apos;&apos;
  ) &amp; BR() &amp;
  TEXT(Address__CountryCode__s)
)</formula>
    <label>Address HTML</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/AddressLabel__c.field-meta.xml
<CustomField>
    <fullName>AddressLabel__c</fullName>
    <formula>IF (
  ISPICKVAL( DeliveryLocationType__c, &apos;Delivery Center&apos; ),
  DeliveryCenter__r.ShippingStreet &amp;
  IF (
    NOT(ISBLANK( DeliveryCenter__r.ShippingCity )),
    &apos;, &apos; &amp; DeliveryCenter__r.ShippingCity,
    &apos;&apos;
  )&amp;
  IF (
    NOT(ISBLANK(DeliveryCenter__r.ShippingState )),
    &apos; &apos; &amp; DeliveryCenter__r.ShippingState,
    &apos;&apos;
  ) &amp;
  IF (
    NOT(ISBLANK( DeliveryCenter__r.ShippingPostalCode )),
    &apos;, &apos; &amp; DeliveryCenter__r.ShippingPostalCode,
    &apos;&apos;
  ),
  DeliveryAddress__Street__s &amp;
  IF (
    NOT(ISBLANK( DeliveryAddress__City__s )),
    &apos;, &apos; &amp; DeliveryAddress__City__s,
    &apos;&apos;
  ) &amp;
  IF (
    NOT(ISBLANK(TEXT(DeliveryAddress__StateCode__s ))),
    &apos; &apos; &amp; TEXT(DeliveryAddress__StateCode__s),
    &apos;&apos;
  ) &amp;
  IF (
    NOT(ISBLANK( DeliveryAddress__PostalCode__s )),
    &apos;, &apos; &amp; DeliveryAddress__PostalCode__s,
    &apos;&apos;
  )
)</formula>
    <label>Address Label</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/DeliveryCenterName__c.field-meta.xml
<CustomField>
    <fullName>DeliveryCenterName__c</fullName>
    <formula>IF(
  ISPICKVAL(LocationType__c, &apos;Delivery Center&apos;),
  DeliveryCenter__r.Name,
  &apos;&apos;
)</formula>
    <label>Delivery Center Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/DeliveryType__c.field-meta.xml
<CustomField>
    <fullName>DeliveryType__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DeliveryType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Delivery Groups</relationshipLabel>
    <relationshipName>DeliveryGroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/recordTypes/Order.recordType-meta.xml
<RecordType>
    <fullName>Order</fullName>
    <active>true</active>
    <label>Order</label>
</RecordType>

force-app/main/default/objects/OrderItem/fields/DeliveryGroup__c.field-meta.xml
<CustomField>
    <fullName>DeliveryGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Delivery Group and the Order Product must be related to the same order.</errorMessage>
        <filterItems>
            <field>$Source.OrderId</field>
            <operation>equals</operation>
            <valueField>DeliveryGroup__c.Order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DeliveryGroup__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>OrderProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DeliveryType__c.field-meta.xml
<CustomField>
    <fullName>DeliveryType__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DeliveryType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PackingSlip__c/PackingSlip__c.object-meta.xml
<CustomObject>
    <label>Packing Slip</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Packing Slip #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packing Slips</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PackingSlip__c/fields/DeliveryGroup__c.field-meta.xml
<CustomField>
    <fullName>DeliveryGroup__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Delivery Group</label>
    <referenceTo>DeliveryGroup__c</referenceTo>
    <relationshipLabel>Packing Slips</relationshipLabel>
    <relationshipName>PackingSlips</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PackingSlip__c/fields/DeliveryType__c.field-meta.xml
<CustomField>
    <fullName>DeliveryType__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Delivery_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PackingSlip__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Packing Slips</relationshipLabel>
    <relationshipName>PackingSlips</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PackingSlipItem__c/PackingSlipItem__c.object-meta.xml
<CustomObject>
    <label>Packing Slip Item</label>
    <nameField>
        <displayFormat>PSI{000000}</displayFormat>
        <label>Packing Slip Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packing Slip Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PackingSlipItem__c/fields/OrderProduct__c.field-meta.xml
<CustomField>
    <fullName>OrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Packing Slip Items</relationshipLabel>
    <relationshipName>PackingSlipItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PackingSlipItem__c/fields/PackingSlip__c.field-meta.xml
<CustomField>
    <fullName>PackingSlip__c</fullName>
    <label>Packing Slip</label>
    <referenceTo>PackingSlip__c</referenceTo>
    <relationshipLabel>Packing Slip Items</relationshipLabel>
    <relationshipName>PackingSlipItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PackingSlipItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <formula>IF(ISBLANK( OrderProduct__r.Product2Id ), &quot;&quot;, HYPERLINK(&quot;/&quot; &amp; OrderProduct__r.Product2Id, OrderProduct__r.Product2.Name, &quot;_blank&quot;))</formula>
    <label>Product</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PackingSlipItem__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/DeliveryType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Delivery</fullName>
        <default>true</default>
        <label>Delivery</label>
    </customValue>
    <customValue>
        <fullName>Installation</fullName>
    </customValue>
    <customValue>
        <fullName>FedEx</fullName>
    </customValue>
    <customValue>
        <fullName>UPS</fullName>
    </customValue>
    <customValue>
        <fullName>DHL</fullName>
    </customValue>
    <customValue>
        <fullName>Courier</fullName>
    </customValue>
    <customValue>
        <fullName>Uber</fullName>
    </customValue>
    <customValue>
        <fullName>Pick Up</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Delivery Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PackingSlipRenderServiceTest.cls
@IsTest
private class PackingSlipRenderServiceTest {
	private static Id buildFakePackingSlipId() {
		return Id.valueOf(PackingSlip__c.SObjectType.getDescribe().getKeyPrefix() + '000000000000AAA');
	}

	private static void primeProviderTestData(Id packingSlipId) {
		PackingSlip__c packingSlip = new PackingSlip__c(
			TrackingNumber__c = 'TRK-300',
			Description__c = 'Handle with care'
		);
		packingSlip.put('Name', 'PS-300');

		Order orderRecord = new Order();
		orderRecord.put('OrderNumber', 'ORD-300');
		packingSlip.putSObject('Order__r', orderRecord);

		SObject deliveryGroupRecord = Schema.getGlobalDescribe().get('DeliveryGroup__c').newSObject();
		deliveryGroupRecord.put('Name', 'Grace Hopper');
		deliveryGroupRecord.put('DeliveryCenterName__c', 'Grace Hopper');
		deliveryGroupRecord.put('AddressLabel__c', 'Grace Hopper');
		deliveryGroupRecord.put('AddressHtml__c', '100 Example Road');
		deliveryGroupRecord.put('DeliveryType__c', 'FedEx');
		packingSlip.putSObject('DeliveryGroup__r', deliveryGroupRecord);

		PackingSlipItem__c itemRecord = new PackingSlipItem__c(
			Quantity__c = 1
		);
		itemRecord.put('Name', 'Item-300');
		itemRecord.put('Product__c', 'Label Printer');
		OrderItem orderProductRecord = new OrderItem();
		orderProductRecord.Description = 'Industrial';
		Product2 productRecord = new Product2(
			Name = 'Label Printer',
			ProductCode = 'SKU-300'
		);
		orderProductRecord.putSObject('Product2', productRecord);
		itemRecord.putSObject('OrderProduct__r', orderProductRecord);

		DefaultPackingSlipDataProvider.setTestData(
			packingSlipId,
			packingSlip,
			new List<PackingSlipItem__c>{ itemRecord }
		);
	}

	@IsTest
	static void renderService_generatesHtmlAndZpl() {
		Id packingSlipId = buildFakePackingSlipId();
		primeProviderTestData(packingSlipId);

		PackingSlipDataModels.TemplateDefinition screenTemplate = new PackingSlipDataModels.TemplateDefinition();
		screenTemplate.templateKey = 'DefaultHtml';
		screenTemplate.name = 'HTML';
		screenTemplate.outputMode = 'SCREEN';
		screenTemplate.providerKey = 'SHIPMENT';
		screenTemplate.isActive = true;
		screenTemplate.source = 'PACKAGED';
		screenTemplate.body = '<div>{{OrderNumber}} {{#each Items}}{{ProductCode}}{{/each}} {{BarcodeSvg}}</div>';

		PackingSlipDataModels.TemplateDefinition zplTemplate = new PackingSlipDataModels.TemplateDefinition();
		zplTemplate.templateKey = 'DefaultZpl';
		zplTemplate.name = 'ZPL';
		zplTemplate.outputMode = 'ZPL';
		zplTemplate.providerKey = 'SHIPMENT';
		zplTemplate.isActive = true;
		zplTemplate.source = 'PACKAGED';
		zplTemplate.body = '^XA^FD{{OrderNumber}}^FS^XZ';

		PackingSlipTemplateRepository.setTestData(
			new List<PackingSlipDataModels.TemplateDefinition>(),
			new List<PackingSlipDataModels.TemplateDefinition>{ screenTemplate, zplTemplate },
			new List<PackingSlipDataModels.FieldMapDefinition>()
		);

		String html = PackingSlipRenderService.previewHtml(packingSlipId, 'DefaultHtml');
		String zpl = PackingSlipRenderService.generateZpl(packingSlipId, 'DefaultZpl');

		System.assert(html.contains('ORD-300'));
		System.assert(html.contains('SKU-300'));
		System.assert(zpl.contains('^XA'));
		System.assert(zpl.contains('ORD-300'));

		PackingSlipTemplateRepository.clearTestData();
		DefaultPackingSlipDataProvider.clearTestData();
	}
}