force-app/main/default/objects/DeliveryGroup__c/DeliveryGroup__c.object-meta.xml
<CustomObject>
    <label>Delivery Group</label>
    <nameField>
        <label>Delivery Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryGroup__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Delivery Groups</relationshipLabel>
    <relationshipName>DeliveryGroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/recordTypes/Order.recordType-meta.xml
<RecordType>
    <fullName>Order</fullName>
    <active>true</active>
    <label>Order</label>
</RecordType>

force-app/main/default/objects/OrderItem/fields/DeliveryGroup__c.field-meta.xml
<CustomField>
    <fullName>DeliveryGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Delivery Group and the Order Product must be related to the same order.</errorMessage>
        <filterItems>
            <field>$Source.OrderId</field>
            <operation>equals</operation>
            <valueField>DeliveryGroup__c.Order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DeliveryGroup__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>OrderProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PackingSlip__c/PackingSlip__c.object-meta.xml
<CustomObject>
    <label>Packing Slip</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Packing Slip #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packing Slips</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PackingSlip__c/fields/DeliveryGroup__c.field-meta.xml
<CustomField>
    <fullName>DeliveryGroup__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Delivery Group</label>
    <referenceTo>DeliveryGroup__c</referenceTo>
    <relationshipLabel>Packing Slips</relationshipLabel>
    <relationshipName>PackingSlips</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PackingSlip__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Packing Slips</relationshipLabel>
    <relationshipName>PackingSlips</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PackingSlipItem__c/PackingSlipItem__c.object-meta.xml
<CustomObject>
    <label>Packing Slip Item</label>
    <nameField>
        <displayFormat>PSI{000000}</displayFormat>
        <label>Packing Slip Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packing Slip Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PackingSlipItem__c/fields/OrderProduct__c.field-meta.xml
<CustomField>
    <fullName>OrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Packing Slip Items</relationshipLabel>
    <relationshipName>PackingSlipItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PackingSlipItem__c/fields/PackingSlip__c.field-meta.xml
<CustomField>
    <fullName>PackingSlip__c</fullName>
    <label>Packing Slip</label>
    <referenceTo>PackingSlip__c</referenceTo>
    <relationshipLabel>Packing Slip Items</relationshipLabel>
    <relationshipName>PackingSlipItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PackingSlipItem__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PackingSlipProviderFactoryTest.cls
@IsTest
private class PackingSlipProviderFactoryTest {
	private static Id buildFakePackingSlipId() {
		return Id.valueOf(PackingSlip__c.SObjectType.getDescribe().getKeyPrefix() + '000000000000AAA');
	}

	private static PackingSlip__c buildTestPackingSlip(String orderNumber, String trackingNumber) {
		PackingSlip__c packingSlip = new PackingSlip__c(
			TrackingNumber__c = trackingNumber,
			Description__c = 'Priority'
		);

		Order orderRecord = (Order)JSON.deserialize(
			'{"OrderNumber":"' + orderNumber + '"}',
			Order.class
		);
		packingSlip.putSObject('Order__r', orderRecord);

		packingSlip.putSObject('DeliveryGroup__r', Schema.getGlobalDescribe().get('DeliveryGroup__c').newSObject());

		return packingSlip;
	}

	private static List<PackingSlipItem__c> buildTestItems() {
		PackingSlipItem__c itemRecord = new PackingSlipItem__c(
			Quantity__c = 4
		);

		OrderItem orderProductRecord = new OrderItem();
		orderProductRecord.Description = 'Red';
		Product2 productRecord = new Product2(
			Name = 'Widget',
			ProductCode = 'SKU-1'
		);
		orderProductRecord.putSObject('Product2', productRecord);
		itemRecord.putSObject('OrderProduct__r', orderProductRecord);

		return new List<PackingSlipItem__c>{ itemRecord };
	}

	@IsTest
	static void factory_resolvesProviderByKeyAndRecordType() {
		Id packingSlipId = buildFakePackingSlipId();

		IPackingSlipDataProvider providerByKey =
			PackingSlipDataProviderFactory.getProviderByKey('SHIPMENT');
		IPackingSlipDataProvider providerByRecord =
			PackingSlipDataProviderFactory.getProviderForRecord(packingSlipId);

		System.assertEquals('SHIPMENT', providerByKey.getProviderKey());
		System.assertEquals('SHIPMENT', providerByRecord.getProviderKey());
	}

	@IsTest
	static void defaultProvider_returnsStructuredDocumentData() {
		Id packingSlipId = buildFakePackingSlipId();
		PackingSlip__c firstGroupPackingSlip = new PackingSlip__c();

		PackingSlip__c secondGroupPackingSlip = new PackingSlip__c(Id = packingSlipId);

		PackingSlip__c thirdGroupPackingSlip = new PackingSlip__c();

		List<PackingSlip__c> groupPackingSlips = new List<PackingSlip__c>{
			firstGroupPackingSlip,
			secondGroupPackingSlip,
			thirdGroupPackingSlip
		};
		PackingSlip__c packingSlip = buildTestPackingSlip('ORD-200', 'TRK-200');
		packingSlip.Id = packingSlipId;
		DefaultPackingSlipDataProvider.setTestData(
			packingSlipId,
			packingSlip,
			buildTestItems(),
			groupPackingSlips
		);

		PackingSlipDataModels.DocumentData document =
			new DefaultPackingSlipDataProvider().getDocumentData(packingSlipId, null);

		System.assertEquals('TRK-200', document.header.trackingNumber);
		System.assertEquals(1, document.items.size());
		System.assertEquals('SKU-1', document.items[0].productCode);
		System.assertEquals(2, document.tokenValues.get('CurrentPackageNumber'));
		System.assertEquals(3, document.tokenValues.get('TotalPackagesInGroup'));
		System.assertEquals('2/3', document.tokenValues.get('PackageSequenceDisplay'));

		DefaultPackingSlipDataProvider.clearTestData();
	}
}