force-app/main/default/objects/DeliveryGroup__c/DeliveryGroup__c.object-meta.xml
<CustomObject>
    <label>Delivery Group</label>
    <nameField>
        <label>Delivery Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryGroup__c/fields/AddressHtml__c.field-meta.xml
<CustomField>
    <fullName>AddressHtml__c</fullName>
    <formula>IF (
  ISPICKVAL( LocationType__c, &apos;Venue&apos; ),
  DeliveryCenter__r.ShippingStreet &amp; BR() &amp;
  DeliveryCenter__r.ShippingCity &amp; &apos; &apos; &amp;
  DeliveryCenter__r.ShippingState &amp;
  IF (
    NOT(ISBLANK( DeliveryCenter__r.ShippingPostalCode )),
    &apos;, &apos; &amp; DeliveryCenter__r.ShippingPostalCode,
    &apos;&apos;
  ) &amp; BR() &amp;
  DeliveryCenter__r.ShippingCountry,
  Address__Street__s &amp; BR() &amp;
  Address__City__s &amp; &apos; &apos; &amp;
  TEXT(Address__StateCode__s) &amp;
  IF (
    NOT(ISBLANK( Address__PostalCode__s )),
    &apos;, &apos; &amp; Address__PostalCode__s,
    &apos;&apos;
  ) &amp; BR() &amp;
  TEXT(Address__CountryCode__s)
)</formula>
    <label>Address HTML</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/AddressLabel__c.field-meta.xml
<CustomField>
    <fullName>AddressLabel__c</fullName>
    <formula>IF (
  ISPICKVAL( DeliveryLocationType__c, &apos;Delivery Center&apos; ),
  DeliveryCenter__r.ShippingStreet &amp;
  IF (
    NOT(ISBLANK( DeliveryCenter__r.ShippingCity )),
    &apos;, &apos; &amp; DeliveryCenter__r.ShippingCity,
    &apos;&apos;
  )&amp;
  IF (
    NOT(ISBLANK(DeliveryCenter__r.ShippingState )),
    &apos; &apos; &amp; DeliveryCenter__r.ShippingState,
    &apos;&apos;
  ) &amp;
  IF (
    NOT(ISBLANK( DeliveryCenter__r.ShippingPostalCode )),
    &apos;, &apos; &amp; DeliveryCenter__r.ShippingPostalCode,
    &apos;&apos;
  ),
  DeliveryAddress__Street__s &amp;
  IF (
    NOT(ISBLANK( DeliveryAddress__City__s )),
    &apos;, &apos; &amp; DeliveryAddress__City__s,
    &apos;&apos;
  ) &amp;
  IF (
    NOT(ISBLANK(TEXT(DeliveryAddress__StateCode__s ))),
    &apos; &apos; &amp; TEXT(DeliveryAddress__StateCode__s),
    &apos;&apos;
  ) &amp;
  IF (
    NOT(ISBLANK( DeliveryAddress__PostalCode__s )),
    &apos;, &apos; &amp; DeliveryAddress__PostalCode__s,
    &apos;&apos;
  )
)</formula>
    <label>Address Label</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/DeliveryCenter__c.field-meta.xml
<CustomField>
    <fullName>DeliveryCenter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Center</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Delivery Groups</relationshipLabel>
    <relationshipName>DeliveryCenter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/DeliveryType__c.field-meta.xml
<CustomField>
    <fullName>DeliveryType__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DeliveryType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/LocationType__c.field-meta.xml
<CustomField>
    <fullName>LocationType__c</fullName>
    <label>Location Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Address</fullName>
            </value>
            <value>
                <fullName>Delivery Center</fullName>
                <default>true</default>
                <label>Delivery Center</label>
            </value>
            <value>
                <fullName>Venue</fullName>
                <isActive>false</isActive>
                <label>Venue</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Delivery Groups</relationshipLabel>
    <relationshipName>DeliveryGroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/recordTypes/Order.recordType-meta.xml
<RecordType>
    <fullName>Order</fullName>
    <active>true</active>
    <label>Order</label>
</RecordType>

force-app/main/default/objects/OrderItem/fields/DeliveryGroup__c.field-meta.xml
<CustomField>
    <fullName>DeliveryGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Delivery Group and the Order Product must be related to the same order.</errorMessage>
        <filterItems>
            <field>$Source.OrderId</field>
            <operation>equals</operation>
            <valueField>DeliveryGroup__c.Order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DeliveryGroup__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>OrderProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DeliveryType__c.field-meta.xml
<CustomField>
    <fullName>DeliveryType__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DeliveryType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DiscountAmount__c.field-meta.xml
<CustomField>
    <fullName>DiscountAmount__c</fullName>
    <description>If the discount type is &quot;Percentage,&quot; this number represents the percentage that will be deducted from the total. If the discount type is &quot;Fixed,&quot; this number represents the exact dollar amount that will be deducted from the total.</description>
    <inlineHelpText>If the discount type is &quot;Percentage,&quot; this number represents the percentage that will be deducted from the total. If the discount type is &quot;Fixed,&quot; this number represents the exact dollar amount that will be deducted from the total.</inlineHelpText>
    <label>Discount Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ParentOrderProduct__c.field-meta.xml
<CustomField>
    <fullName>ParentOrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>ChildOrderProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/WorkOrderStatus__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderStatus__c</fullName>
    <label>Work Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PackingSlip__c/PackingSlip__c.object-meta.xml
<CustomObject>
    <label>Packing Slip</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Packing Slip #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packing Slips</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PackingSlip__c/fields/DeliveryGroup__c.field-meta.xml
<CustomField>
    <fullName>DeliveryGroup__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Delivery Group</label>
    <referenceTo>DeliveryGroup__c</referenceTo>
    <relationshipLabel>Packing Slips</relationshipLabel>
    <relationshipName>PackingSlips</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PackingSlip__c/fields/DeliveryType__c.field-meta.xml
<CustomField>
    <fullName>DeliveryType__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Delivery_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PackingSlip__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Packing Slips</relationshipLabel>
    <relationshipName>PackingSlips</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PackingSlipItem__c/PackingSlipItem__c.object-meta.xml
<CustomObject>
    <label>Packing Slip Item</label>
    <nameField>
        <displayFormat>PSI{000000}</displayFormat>
        <label>Packing Slip Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packing Slip Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PackingSlipItem__c/fields/OrderProduct__c.field-meta.xml
<CustomField>
    <fullName>OrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Packing Slip Items</relationshipLabel>
    <relationshipName>PackingSlipItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PackingSlipItem__c/fields/PackingSlip__c.field-meta.xml
<CustomField>
    <fullName>PackingSlip__c</fullName>
    <label>Packing Slip</label>
    <referenceTo>PackingSlip__c</referenceTo>
    <relationshipLabel>Packing Slip Items</relationshipLabel>
    <relationshipName>PackingSlipItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PackingSlipItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <formula>IF(ISBLANK( OrderProduct__r.Product2Id ), &quot;&quot;, HYPERLINK(&quot;/&quot; &amp; OrderProduct__r.Product2Id, OrderProduct__r.Product2.Name, &quot;_blank&quot;))</formula>
    <label>Product</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PackingSlipItem__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Finish__c.field-meta.xml
<CustomField>
    <fullName>Finish__c</fullName>
    <label>Finish</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Finishing</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/DeliveryType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Delivery</fullName>
        <default>true</default>
        <label>Delivery</label>
    </customValue>
    <customValue>
        <fullName>Installation</fullName>
    </customValue>
    <customValue>
        <fullName>FedEx</fullName>
    </customValue>
    <customValue>
        <fullName>UPS</fullName>
    </customValue>
    <customValue>
        <fullName>DHL</fullName>
    </customValue>
    <customValue>
        <fullName>Courier</fullName>
    </customValue>
    <customValue>
        <fullName>Uber</fullName>
    </customValue>
    <customValue>
        <fullName>Pick Up</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Delivery Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Finishing.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
        <default>true</default>
        <label>Standard</label>
    </customValue>
    <customValue>
        <fullName>Deluxe</fullName>
    </customValue>
    <customValue>
        <fullName>Matte</fullName>
    </customValue>
    <customValue>
        <fullName>Gloss</fullName>
    </customValue>
    <customValue>
        <fullName>Semi-Gloss</fullName>
    </customValue>
    <customValue>
        <fullName>Dry Erase</fullName>
    </customValue>
    <customValue>
        <fullName>Double Sided</fullName>
    </customValue>
    <customValue>
        <fullName>UV Coating</fullName>
    </customValue>
    <customValue>
        <fullName>No Coating</fullName>
    </customValue>
    <customValue>
        <fullName>Spot UV in both sides</fullName>
    </customValue>
    <customValue>
        <fullName>Spot UV on one side</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Finishing</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PackingSlipManager.cls
/**
 * Packing Slip manager. Main functionality involving PackingSlip__c and PackingSlipItem__c objects.
 * @author Fernando Gomez
 * @version 1.0 12/16/2025
 */
public with sharing class PackingSlipManager {

	/**
	 * Gets all Packing Slips for a given Order with their related Packing Slip Items
	 * @param orderId The Order Id
	 * @return List of PackingSlip__c records with related PackingSlipItem__c records
	 */
	@AuraEnabled(cacheable=true)
	public static List<DeliveryGroup__c> getPackingSlipsForOrder(Id orderId) {
		try {
			return [
				SELECT Name,
					AddressLabel__c,
					AddressHtml__c,
					Address__City__s,
					Address__CountryCode__s,
					Address__GeocodeAccuracy__s,
					Address__Latitude__s,
					Address__Longitude__s,
					Address__PostalCode__s,
					Address__StateCode__s,
					Address__Street__s,
					DueDate__c,
					DeliveryType__c,
					LocationType__c,
					Order__c,
					DeliveryCenter__c,
					DeliveryCenter__r.Name,
					(
						SELECT Name,
							Description__c,
							TrackingNumber__c
						FROM PackingSlips__r
						ORDER BY Name
					)
				FROM DeliveryGroup__c
				WHERE Order__c = :orderId
				ORDER BY Name
			];
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
	}

	/**
	 * Gets all Order Products for a given Order
	 * @param orderId The Order Id
	 * @return List of OrderItem records
	 */
	@AuraEnabled(cacheable=true)
	public static List<OrderItem> getOrderProductsForOrder(Id orderId) {
		try {
			return [
				SELECT AvailableQuantity,
					BasePrice__c,
					CreatedDate,
					DeliveryType__c,
					Width__c,
					Height__c,
					Depth__c,
					Description,
					DiscountType__c,
					DiscountAmount__c,
					EndDate,
					ListPrice,
					Notes__c,
					Quantity,
					TotalPrice,
					UnitPrice,
					UnitType__c,
					WorkOrderStatus__c,
					DeliveryGroup__c,
					DeliveryGroup__r.Name,
					DeliveryGroup__r.DueDate__c,
					OrderId,
					PricebookEntryId,
					ParentOrderProduct__c,
					ParentOrderProduct__r.Product2.Name,
					Product2Id,
					Product2.Name,
					Product2.ProductCode,
					Product2.Finish__c,
					Product2.Material__c,
					Product2.Material__r.Name,
					Product2.RecordTypeId,
					Product2.RecordType.DeveloperName
				FROM OrderItem
				WHERE OrderId = :orderId
				ORDER BY OrderItemNumber
			];
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
	}

	/**
	 * Gets a single Packing Slip with its items and available order products
	 * @param packingSlipId The Packing Slip Id
	 * @return Map containing PackingSlip data, items, and available order products
	 */
	@AuraEnabled(cacheable=true)
	public static Map<String, Object> getPackingSlipWithItems(Id packingSlipId) {
		try {
			// Get the packing slip with items
			PackingSlip__c packingSlip = [
				SELECT Id, Name, 
					Description__c, 
					TrackingNumber__c,
					Order__c,
					DeliveryGroup__c,
					DeliveryGroup__r.Name,
					(
						SELECT Id, 
							Name,
							OrderProduct__c,
							OrderProduct__r.AvailableQuantity,
							OrderProduct__r.BasePrice__c,
							OrderProduct__r.CreatedDate,
							OrderProduct__r.DeliveryGroup__c,
							OrderProduct__r.DeliveryType__c,
							OrderProduct__r.Width__c,
							OrderProduct__r.Height__c,
							OrderProduct__r.Depth__c,
							OrderProduct__r.Description,
							OrderProduct__r.DiscountType__c,
							OrderProduct__r.DiscountAmount__c,
							OrderProduct__r.EndDate,
							OrderProduct__r.ListPrice,
							OrderProduct__r.Notes__c,
							OrderProduct__r.Quantity,
							OrderProduct__r.TotalPrice,
							OrderProduct__r.UnitPrice,
							OrderProduct__r.UnitType__c,
							OrderProduct__r.WorkOrderStatus__c,
							OrderProduct__r.OrderId,
							OrderProduct__r.PricebookEntryId,
							OrderProduct__r.ParentOrderProduct__c,
							OrderProduct__r.ParentOrderProduct__r.Product2.Name,
							OrderProduct__r.Product2Id,
							OrderProduct__r.Product2.Name,
							OrderProduct__r.Product2.ProductCode,
							OrderProduct__r.Product2.Finish__c,
							OrderProduct__r.Product2.Material__c,
							OrderProduct__r.Product2.Material__r.Name,
							OrderProduct__r.Product2.RecordTypeId,
							OrderProduct__r.Product2.RecordType.DeveloperName,
							Quantity__c
							// Description__c,
							// Product__c
						FROM PackingSlipItems__r
						ORDER BY CreatedDate
					)
				FROM PackingSlip__c
				WHERE Id = :packingSlipId
				LIMIT 1
			];

			// Get all order products from the same delivery group
			List<OrderItem> orderProducts = [
				SELECT AvailableQuantity,
					BasePrice__c,
					CreatedDate,
					DeliveryGroup__c,
					DeliveryType__c,
					Width__c,
					Height__c,
					Depth__c,
					Description,
					DiscountType__c,
					DiscountAmount__c,
					EndDate,
					ListPrice,
					Notes__c,
					Quantity,
					TotalPrice,
					UnitPrice,
					UnitType__c,
					WorkOrderStatus__c,
					OrderId,
					PricebookEntryId,
					ParentOrderProduct__c,
					ParentOrderProduct__r.Product2.Name,
					Product2Id,
					Product2.Name,
					Product2.ProductCode,
					Product2.Finish__c,
					Product2.Material__c,
					Product2.Material__r.Name,
					Product2.RecordTypeId,
					Product2.RecordType.DeveloperName
				FROM OrderItem
				WHERE DeliveryGroup__c = :packingSlip.DeliveryGroup__c
				ORDER BY OrderItemNumber
			];

			// Build packed quantity baseline from other packing slips in the same delivery group.
			Map<String, Decimal> packedQtyByOrderProductId = new Map<String, Decimal>();
			for (AggregateResult ar : [
				SELECT OrderProduct__c orderProductId, SUM(Quantity__c) totalQty
				FROM PackingSlipItem__c
				WHERE PackingSlip__r.DeliveryGroup__c = :packingSlip.DeliveryGroup__c
					AND PackingSlip__c != :packingSlipId
				GROUP BY OrderProduct__c
			]) {
				Id orderProductId = (Id)ar.get('orderProductId');
				Decimal totalQty = (Decimal)ar.get('totalQty');
				if (orderProductId != null)
					packedQtyByOrderProductId.put(String.valueOf(orderProductId), totalQty == null ? 0 : totalQty);
			}

			return new Map<String, Object>{
				'packingSlip' => packingSlip,
				'orderProducts' => orderProducts,
				'packedQtyByOrderProductId' => packedQtyByOrderProductId
			};
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
	}

	/**
	 * Saves Packing Slip Items
	 * @param packingSlipItems List of PackingSlipItem__c records to save
	 * @param packingSlipItemIdsToDelete List of PackingSlipItem__c Ids to delete
	 * @return List of saved PackingSlipItem__c records
	 */
	@AuraEnabled
	public static List<PackingSlipItem__c> savePackingSlipItems(
		List<PackingSlipItem__c> packingSlipItems,
		List<Id> packingSlipItemIdsToDelete
	) {
		try {
			if (packingSlipItemIdsToDelete != null && !packingSlipItemIdsToDelete.isEmpty()) {
				delete [
					SELECT Id
					FROM PackingSlipItem__c
					WHERE Id IN :packingSlipItemIdsToDelete
				];
			}

			if (packingSlipItems != null && !packingSlipItems.isEmpty()) {
				upsert packingSlipItems;
			}

			return packingSlipItems;
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
	}

	/**
	 * Deletes a Packing Slip by Id
	 * @param packingSlipId The Packing Slip Id
	 */
	@AuraEnabled
	public static void deletePackingSlip(Id packingSlipId) {
		try {
			delete [
				SELECT Id
				FROM PackingSlip__c
				WHERE Id = :packingSlipId
				LIMIT 1
			];
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
	}
}