force-app/main/default/objects/DeliveryGroup__c/DeliveryGroup__c.object-meta.xml
<CustomObject>
    <label>Delivery Group</label>
    <nameField>
        <label>Delivery Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryGroup__c/fields/DeliveryCenter__c.field-meta.xml
<CustomField>
    <fullName>DeliveryCenter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Center</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Delivery Groups</relationshipLabel>
    <relationshipName>DeliveryCenter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/DeliveryLocationType__c.field-meta.xml
<CustomField>
    <fullName>DeliveryLocationType__c</fullName>
    <label>Location Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Address</fullName>
            </value>
            <value>
                <fullName>Delivery Center</fullName>
                <default>true</default>
                <label>Delivery Center</label>
            </value>
            <value>
                <fullName>Venue</fullName>
                <isActive>false</isActive>
                <label>Venue</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/DeliveryType__c.field-meta.xml
<CustomField>
    <fullName>DeliveryType__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DeliveryType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Delivery Groups</relationshipLabel>
    <relationshipName>DeliveryGroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Delivery Groups</relationshipLabel>
    <relationshipName>DeliveryGroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/PickupCenter__c.field-meta.xml
<CustomField>
    <fullName>PickupCenter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pickup Center</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Delivery Groups</relationshipLabel>
    <relationshipName>PickupCenter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/PickupLocationType__c.field-meta.xml
<CustomField>
    <fullName>PickupLocationType__c</fullName>
    <label>Pickup Location Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Address</fullName>
            </value>
            <value>
                <fullName>Pickup Center</fullName>
                <default>true</default>
                <label>Pickup Center</label>
            </value>
            <value>
                <fullName>Venue</fullName>
                <isActive>false</isActive>
                <label>Venue</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/DeliveryGroup__c/recordTypes/Order.recordType-meta.xml
<RecordType>
    <fullName>Order</fullName>
    <active>true</active>
    <label>Order</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/BasePrice__c.field-meta.xml
<CustomField>
    <fullName>BasePrice__c</fullName>
    <label>Base Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/DeliveryGroup__c.field-meta.xml
<CustomField>
    <fullName>DeliveryGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Delivery Group and the Opportunity Product must be related to the same opportunity.</errorMessage>
        <filterItems>
            <field>$Source.OpportunityId</field>
            <operation>equals</operation>
            <valueField>DeliveryGroup__c.Opportunity__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DeliveryGroup__c</referenceTo>
    <relationshipLabel>Opportunity Products</relationshipLabel>
    <relationshipName>OpportunityProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Depth__c.field-meta.xml
<CustomField>
    <fullName>Depth__c</fullName>
    <label>Depth</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/DiscountType__c.field-meta.xml
<CustomField>
    <fullName>DiscountType__c</fullName>
    <label>Discount Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DiscountType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Height__c</fullName>
    <label>Height</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/ParentOrderProduct__c.field-meta.xml
<CustomField>
    <fullName>ParentOrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Opportunity Product</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Opportunity Products</relationshipLabel>
    <relationshipName>ChildOpportunityProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/UnitType__c.field-meta.xml
<CustomField>
    <fullName>UnitType__c</fullName>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>UnitType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Width__c.field-meta.xml
<CustomField>
    <fullName>Width__c</fullName>
    <label>Width</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DeliveryGroup__c.field-meta.xml
<CustomField>
    <fullName>DeliveryGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Delivery Group and the Order Product must be related to the same order.</errorMessage>
        <filterItems>
            <field>$Source.OrderId</field>
            <operation>equals</operation>
            <valueField>DeliveryGroup__c.Order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DeliveryGroup__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>OrderProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DeliveryType__c.field-meta.xml
<CustomField>
    <fullName>DeliveryType__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DeliveryType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DiscountAmount__c.field-meta.xml
<CustomField>
    <fullName>DiscountAmount__c</fullName>
    <description>If the discount type is &quot;Percentage,&quot; this number represents the percentage that will be deducted from the total. If the discount type is &quot;Fixed,&quot; this number represents the exact dollar amount that will be deducted from the total.</description>
    <inlineHelpText>If the discount type is &quot;Percentage,&quot; this number represents the percentage that will be deducted from the total. If the discount type is &quot;Fixed,&quot; this number represents the exact dollar amount that will be deducted from the total.</inlineHelpText>
    <label>Discount Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ParentOrderProduct__c.field-meta.xml
<CustomField>
    <fullName>ParentOrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>ChildOrderProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/WorkOrderStatus__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderStatus__c</fullName>
    <label>Work Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/DeliveryType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Delivery</fullName>
        <default>true</default>
        <label>Delivery</label>
    </customValue>
    <customValue>
        <fullName>Installation</fullName>
    </customValue>
    <customValue>
        <fullName>FedEx</fullName>
    </customValue>
    <customValue>
        <fullName>UPS</fullName>
    </customValue>
    <customValue>
        <fullName>DHL</fullName>
    </customValue>
    <customValue>
        <fullName>Courier</fullName>
    </customValue>
    <customValue>
        <fullName>Uber</fullName>
    </customValue>
    <customValue>
        <fullName>Pick Up</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Delivery Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/DiscountType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Fixed Amount</fullName>
    </customValue>
    <customValue>
        <fullName>Percentage</fullName>
    </customValue>
    <description>A &quot;percentage discount&quot; means a deduction from the original price based on a specific percentage, while a &quot;fixed amount discount&quot; refers to subtracting a set dollar amount from the original price, regardless of the item&apos;s cost; essentially, a percentage d</description>
    <masterLabel>Discount Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/UnitType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Each</fullName>
    </customValue>
    <customValue>
        <fullName>SqFt</fullName>
    </customValue>
    <customValue>
        <fullName>Hour</fullName>
    </customValue>
    <masterLabel>Unit Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DeliveryGroupCloneService.cls
/**
 * Shared cloning service for Delivery Groups and related line items.
 */
public with sharing class DeliveryGroupCloneService {

	public static void cloneOrderDeliveryGroupsAndItems(
		List<Order> targetOrders,
		List<Order> sourceOrders
	) {
		if (targetOrders == null || sourceOrders == null || targetOrders.isEmpty() || sourceOrders.isEmpty()) {
			return;
		}

		Map<Id, Id> sourceToTargetOrderId = new Map<Id, Id>();
		for (Integer i = 0; i < targetOrders.size() && i < sourceOrders.size(); i++) {
			if (targetOrders[i] != null && targetOrders[i].Id != null && sourceOrders[i] != null && sourceOrders[i].Id != null) {
				sourceToTargetOrderId.put(sourceOrders[i].Id, targetOrders[i].Id);
			}
		}

		if (sourceToTargetOrderId.isEmpty()) {
			return;
		}

		List<DeliveryGroup__c> sourceGroups = [
			SELECT Id,
				Name,
				DeliveryAddress__City__s,
				DeliveryAddress__CountryCode__s,
				DeliveryAddress__GeocodeAccuracy__s,
				DeliveryAddress__Latitude__s,
				DeliveryAddress__Longitude__s,
				DeliveryAddress__PostalCode__s,
				DeliveryAddress__StateCode__s,
				DeliveryAddress__Street__s,
				CreatedDate,
				DueDate__c,
				DeliveryType__c,
				DeliveryLocationType__c,
				PickupLocationType__c,
				Order__c,
				DeliveryCenter__c,
				PickupCenter__c,
				(
					SELECT Id,
						AvailableQuantity,
						BasePrice__c,
						DeliveryGroup__c,
						DeliveryType__c,
						Width__c,
						Height__c,
						Depth__c,
						Description,
						DiscountType__c,
						DiscountAmount__c,
						EndDate,
						ListPrice,
						Notes__c,
						Quantity,
						TotalPrice,
						UnitPrice,
						UnitType__c,
						WorkOrderStatus__c,
						OrderId,
						ParentOrderProduct__c,
						PricebookEntryId,
						Product2Id
					FROM OrderProducts__r
					ORDER BY CreatedDate ASC
				)
			FROM DeliveryGroup__c
			WHERE Order__c IN :sourceToTargetOrderId.keySet()
			ORDER BY CreatedDate ASC
		];

		Map<Id, DeliveryGroup__c> targetGroupBySourceGroupId = new Map<Id, DeliveryGroup__c>();
		Map<Id, List<OrderItem>> sourceItemsBySourceGroupId = new Map<Id, List<OrderItem>>();

		for (DeliveryGroup__c sourceGroup : sourceGroups) {
			DeliveryGroup__c targetGroup = sourceGroup.clone(false, true, false, false);
			targetGroup.Order__c = sourceToTargetOrderId.get(sourceGroup.Order__c);
			targetGroup.Opportunity__c = null;
			targetGroupBySourceGroupId.put(sourceGroup.Id, targetGroup);
			sourceItemsBySourceGroupId.put(sourceGroup.Id, sourceGroup.OrderProducts__r.deepClone(false, false, false));
		}

		if (!targetGroupBySourceGroupId.isEmpty()) {
			insert targetGroupBySourceGroupId.values();
		}

		List<OrderItem> itemsToInsert = new List<OrderItem>();
		List<Id> sourceItemIdsInOrder = new List<Id>();
		Map<Id, Id> sourceParentBySourceItemId = new Map<Id, Id>();

		for (Id sourceGroupId : targetGroupBySourceGroupId.keySet()) {
			DeliveryGroup__c targetGroup = targetGroupBySourceGroupId.get(sourceGroupId);
			for (OrderItem clonedItem : sourceItemsBySourceGroupId.get(sourceGroupId)) {
				Id sourceItemId = clonedItem.Id;
				Id sourceParentId = clonedItem.ParentOrderProduct__c;
				clonedItem.DeliveryGroup__c = targetGroup.Id;
				clonedItem.OrderId = targetGroup.Order__c;
				clonedItem.ParentOrderProduct__c = null;
				itemsToInsert.add(clonedItem);
				sourceItemIdsInOrder.add(sourceItemId);
				sourceParentBySourceItemId.put(sourceItemId, sourceParentId);
			}
		}

		List<OrderItem> sourceUngroupedDiscounts = [
			SELECT Id,
				AvailableQuantity,
				BasePrice__c,
				DeliveryGroup__c,
				DeliveryType__c,
				Width__c,
				Height__c,
				Depth__c,
				Description,
				DiscountType__c,
				DiscountAmount__c,
				EndDate,
				ListPrice,
				Notes__c,
				Quantity,
				TotalPrice,
				UnitPrice,
				UnitType__c,
				WorkOrderStatus__c,
				OrderId,
				ParentOrderProduct__c,
				PricebookEntryId,
				Product2Id
			FROM OrderItem
			WHERE OrderId IN :sourceToTargetOrderId.keySet()
			AND DeliveryGroup__c = null
			AND Product2.RecordType.DeveloperName = 'Discount'
			ORDER BY CreatedDate ASC
		];

		for (OrderItem sourceDiscount : sourceUngroupedDiscounts) {
			OrderItem clonedDiscount = sourceDiscount.clone(false, true, false, false);
			Id sourceItemId = clonedDiscount.Id;
			Id sourceParentId = clonedDiscount.ParentOrderProduct__c;
			clonedDiscount.OrderId = sourceToTargetOrderId.get(sourceDiscount.OrderId);
			clonedDiscount.DeliveryGroup__c = null;
			clonedDiscount.ParentOrderProduct__c = null;
			itemsToInsert.add(clonedDiscount);
			sourceItemIdsInOrder.add(sourceItemId);
			sourceParentBySourceItemId.put(sourceItemId, sourceParentId);
		}

		if (itemsToInsert.isEmpty()) {
			return;
		}

		insert itemsToInsert;

		Map<Id, Id> newItemIdBySourceItemId = new Map<Id, Id>();
		for (Integer i = 0; i < itemsToInsert.size(); i++) {
			newItemIdBySourceItemId.put(sourceItemIdsInOrder[i], itemsToInsert[i].Id);
		}

		List<OrderItem> parentUpdates = new List<OrderItem>();
		for (Id sourceItemId : sourceItemIdsInOrder) {
			Id sourceParentId = sourceParentBySourceItemId.get(sourceItemId);
			if (sourceParentId != null && newItemIdBySourceItemId.containsKey(sourceParentId)) {
				parentUpdates.add(new OrderItem(
					Id = newItemIdBySourceItemId.get(sourceItemId),
					ParentOrderProduct__c = newItemIdBySourceItemId.get(sourceParentId)
				));
			}
		}

		if (!parentUpdates.isEmpty()) {
			update parentUpdates;
		}
	}

	public static void cloneOpportunityDeliveryGroupsAndItems(
		List<Opportunity> targetOpportunities,
		List<Opportunity> sourceOpportunities
	) {
		if (
			targetOpportunities == null ||
			sourceOpportunities == null ||
			targetOpportunities.isEmpty() ||
			sourceOpportunities.isEmpty()
		) {
			return;
		}

		Map<Id, Id> sourceToTargetOpportunityId = new Map<Id, Id>();
		for (Integer i = 0; i < targetOpportunities.size() && i < sourceOpportunities.size(); i++) {
			if (
				targetOpportunities[i] != null && targetOpportunities[i].Id != null &&
				sourceOpportunities[i] != null && sourceOpportunities[i].Id != null
			) {
				sourceToTargetOpportunityId.put(sourceOpportunities[i].Id, targetOpportunities[i].Id);
			}
		}

		if (sourceToTargetOpportunityId.isEmpty()) {
			return;
		}

		List<DeliveryGroup__c> sourceGroups = [
			SELECT Id,
				Name,
				DeliveryAddress__City__s,
				DeliveryAddress__CountryCode__s,
				DeliveryAddress__GeocodeAccuracy__s,
				DeliveryAddress__Latitude__s,
				DeliveryAddress__Longitude__s,
				DeliveryAddress__PostalCode__s,
				DeliveryAddress__StateCode__s,
				DeliveryAddress__Street__s,
				CreatedDate,
				DueDate__c,
				DeliveryType__c,
				DeliveryLocationType__c,
				PickupLocationType__c,
				Opportunity__c,
				DeliveryCenter__c,
				PickupCenter__c,
				(
					SELECT Id,
						BasePrice__c,
						DeliveryGroup__c,
						DeliveryType__c,
						Width__c,
						Height__c,
						Depth__c,
						Description,
						DiscountType__c,
						DiscountAmount__c,
						ListPrice,
						Notes__c,
						OpportunityId,
						ParentOrderProduct__c,
						PricebookEntryId,
						Product2Id,
						Quantity,
						TotalPrice,
						UnitPrice,
						UnitType__c,
						WorkOrderStatus__c
					FROM OpportunityProducts__r
					ORDER BY CreatedDate ASC
				)
			FROM DeliveryGroup__c
			WHERE Opportunity__c IN :sourceToTargetOpportunityId.keySet()
			ORDER BY CreatedDate ASC
		];

		Map<Id, DeliveryGroup__c> targetGroupBySourceGroupId = new Map<Id, DeliveryGroup__c>();
		Map<Id, List<OpportunityLineItem>> sourceItemsBySourceGroupId =
			new Map<Id, List<OpportunityLineItem>>();

		for (DeliveryGroup__c sourceGroup : sourceGroups) {
			DeliveryGroup__c targetGroup = sourceGroup.clone(false, true, false, false);
			targetGroup.Opportunity__c = sourceToTargetOpportunityId.get(sourceGroup.Opportunity__c);
			targetGroup.Order__c = null;
			targetGroupBySourceGroupId.put(sourceGroup.Id, targetGroup);
			sourceItemsBySourceGroupId.put(sourceGroup.Id, sourceGroup.OpportunityProducts__r.deepClone(false, false, false));
		}

		if (!targetGroupBySourceGroupId.isEmpty()) {
			insert targetGroupBySourceGroupId.values();
		}

		List<OpportunityLineItem> itemsToInsert = new List<OpportunityLineItem>();
		List<Id> sourceItemIdsInOrder = new List<Id>();
		Map<Id, Id> sourceParentBySourceItemId = new Map<Id, Id>();

		for (Id sourceGroupId : targetGroupBySourceGroupId.keySet()) {
			DeliveryGroup__c targetGroup = targetGroupBySourceGroupId.get(sourceGroupId);
			for (OpportunityLineItem clonedItem : sourceItemsBySourceGroupId.get(sourceGroupId)) {
				Id sourceItemId = clonedItem.Id;
				Id sourceParentId = clonedItem.ParentOrderProduct__c;
				clonedItem.DeliveryGroup__c = targetGroup.Id;
				clonedItem.OpportunityId = targetGroup.Opportunity__c;
				clonedItem.ParentOrderProduct__c = null;
				clonedItem.TotalPrice = null;
				itemsToInsert.add(clonedItem);
				sourceItemIdsInOrder.add(sourceItemId);
				sourceParentBySourceItemId.put(sourceItemId, sourceParentId);
			}
		}

		List<OpportunityLineItem> sourceUngroupedDiscounts = [
			SELECT Id,
				BasePrice__c,
				DeliveryGroup__c,
				DeliveryType__c,
				Width__c,
				Height__c,
				Depth__c,
				Description,
				DiscountType__c,
				DiscountAmount__c,
				ListPrice,
				Notes__c,
				OpportunityId,
				ParentOrderProduct__c,
				PricebookEntryId,
				Product2Id,
				Quantity,
				TotalPrice,
				UnitPrice,
				UnitType__c,
				WorkOrderStatus__c
			FROM OpportunityLineItem
			WHERE OpportunityId IN :sourceToTargetOpportunityId.keySet()
			AND DeliveryGroup__c = null
			AND Product2.RecordType.DeveloperName = 'Discount'
			ORDER BY CreatedDate ASC
		];

		for (OpportunityLineItem sourceDiscount : sourceUngroupedDiscounts) {
			OpportunityLineItem clonedDiscount = sourceDiscount.clone(false, true, false, false);
			Id sourceItemId = clonedDiscount.Id;
			Id sourceParentId = clonedDiscount.ParentOrderProduct__c;
			clonedDiscount.OpportunityId = sourceToTargetOpportunityId.get(sourceDiscount.OpportunityId);
			clonedDiscount.DeliveryGroup__c = null;
			clonedDiscount.ParentOrderProduct__c = null;
			clonedDiscount.TotalPrice = null;
			itemsToInsert.add(clonedDiscount);
			sourceItemIdsInOrder.add(sourceItemId);
			sourceParentBySourceItemId.put(sourceItemId, sourceParentId);
		}

		if (itemsToInsert.isEmpty()) {
			return;
		}

		insert itemsToInsert;

		Map<Id, Id> newItemIdBySourceItemId = new Map<Id, Id>();
		for (Integer i = 0; i < itemsToInsert.size(); i++) {
			newItemIdBySourceItemId.put(sourceItemIdsInOrder[i], itemsToInsert[i].Id);
		}

		List<OpportunityLineItem> parentUpdates = new List<OpportunityLineItem>();
		for (Id sourceItemId : sourceItemIdsInOrder) {
			Id sourceParentId = sourceParentBySourceItemId.get(sourceItemId);
			if (sourceParentId != null && newItemIdBySourceItemId.containsKey(sourceParentId)) {
				parentUpdates.add(new OpportunityLineItem(
					Id = newItemIdBySourceItemId.get(sourceItemId),
					ParentOrderProduct__c = newItemIdBySourceItemId.get(sourceParentId)
				));
			}
		}

		if (!parentUpdates.isEmpty()) {
			update parentUpdates;
		}
	}
}