force-app/main/default/objects/DeliveryGroup__c/DeliveryGroup__c.object-meta.xml
<CustomObject>
    <label>Delivery Group</label>
    <nameField>
        <label>Delivery Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryGroup__c/fields/AddressLabel__c.field-meta.xml
<CustomField>
    <fullName>AddressLabel__c</fullName>
    <formula>IF (
  ISPICKVAL( DeliveryLocationType__c, &apos;Delivery Center&apos; ),
  DeliveryCenter__r.ShippingStreet &amp;
  IF (
    NOT(ISBLANK( DeliveryCenter__r.ShippingCity )),
    &apos;, &apos; &amp; DeliveryCenter__r.ShippingCity,
    &apos;&apos;
  )&amp;
  IF (
    NOT(ISBLANK(DeliveryCenter__r.ShippingState )),
    &apos; &apos; &amp; DeliveryCenter__r.ShippingState,
    &apos;&apos;
  ) &amp;
  IF (
    NOT(ISBLANK( DeliveryCenter__r.ShippingPostalCode )),
    &apos;, &apos; &amp; DeliveryCenter__r.ShippingPostalCode,
    &apos;&apos;
  ),
  DeliveryAddress__Street__s &amp;
  IF (
    NOT(ISBLANK( DeliveryAddress__City__s )),
    &apos;, &apos; &amp; DeliveryAddress__City__s,
    &apos;&apos;
  ) &amp;
  IF (
    NOT(ISBLANK(TEXT(DeliveryAddress__StateCode__s ))),
    &apos; &apos; &amp; TEXT(DeliveryAddress__StateCode__s),
    &apos;&apos;
  ) &amp;
  IF (
    NOT(ISBLANK( DeliveryAddress__PostalCode__s )),
    &apos;, &apos; &amp; DeliveryAddress__PostalCode__s,
    &apos;&apos;
  )
)</formula>
    <label>Address Label</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/DeliveryAddressHtml__c.field-meta.xml
<CustomField>
    <fullName>DeliveryAddressHtml__c</fullName>
    <formula>IF (
  ISPICKVAL( DeliveryLocationType__c, &apos;Delivery Center&apos; ),
  DeliveryCenter__r.ShippingStreet &amp; " " &amp;
  DeliveryCenter__r.ShippingCity &amp; &apos; &apos; &amp;
  DeliveryCenter__r.ShippingState &amp;
  IF (
    NOT(ISBLANK( DeliveryCenter__r.ShippingPostalCode )),
    &apos;, &apos; &amp; DeliveryCenter__r.ShippingPostalCode,
    &apos;&apos;
  ) &amp; " " &amp;
  DeliveryCenter__r.ShippingCountry,
  DeliveryAddress__Street__s &amp; " " &amp;
  DeliveryAddress__City__s &amp; &apos; &apos; &amp;
  TEXT(DeliveryAddress__StateCode__s) &amp;
  IF (
    NOT(ISBLANK( DeliveryAddress__PostalCode__s )),
    &apos;, &apos; &amp; DeliveryAddress__PostalCode__s,
    &apos;&apos;
  ) &amp; " " &amp;
  TEXT(DeliveryAddress__CountryCode__s)
)</formula>
    <label>Delivery Address HTML</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/DeliveryCenter__c.field-meta.xml
<CustomField>
    <fullName>DeliveryCenter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Center</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Delivery Groups</relationshipLabel>
    <relationshipName>DeliveryCenter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/DeliveryLocationType__c.field-meta.xml
<CustomField>
    <fullName>DeliveryLocationType__c</fullName>
    <label>Location Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Address</fullName>
            </value>
            <value>
                <fullName>Delivery Center</fullName>
                <default>true</default>
                <label>Delivery Center</label>
            </value>
            <value>
                <fullName>Venue</fullName>
                <isActive>false</isActive>
                <label>Venue</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/DeliveryType__c.field-meta.xml
<CustomField>
    <fullName>DeliveryType__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DeliveryType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Delivery Groups</relationshipLabel>
    <relationshipName>DeliveryGroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/PickupAddressHtml__c.field-meta.xml
<CustomField>
    <fullName>PickupAddressHtml__c</fullName>
    <formula>IF (
  ISPICKVAL( PickupLocationType__c, &apos;Pickup Center&apos; ),
  PickupCenter__r.ShippingStreet &amp; " " &amp;
  PickupCenter__r.ShippingCity &amp; &apos; &apos; &amp;
  PickupCenter__r.ShippingState &amp;
  IF (
    NOT(ISBLANK( PickupCenter__r.ShippingPostalCode )),
    &apos;, &apos; &amp; PickupCenter__r.ShippingPostalCode,
    &apos;&apos;
  ) &amp; " " &amp;
  PickupCenter__r.ShippingCountry,
  PickupAddress__Street__s &amp; " " &amp;
  PickupAddress__City__s &amp; &apos; &apos; &amp;
  TEXT(PickupAddress__StateCode__s) &amp;
  IF (
    NOT(ISBLANK( PickupAddress__PostalCode__s )),
    &apos;, &apos; &amp; PickupAddress__PostalCode__s,
    &apos;&apos;
  ) &amp; " " &amp;
  TEXT(PickupAddress__CountryCode__s)
)</formula>
    <label>Pickup Address HTML</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/PickupCenter__c.field-meta.xml
<CustomField>
    <fullName>PickupCenter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pickup Center</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Delivery Groups</relationshipLabel>
    <relationshipName>PickupCenter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/PickupLocationType__c.field-meta.xml
<CustomField>
    <fullName>PickupLocationType__c</fullName>
    <label>Pickup Location Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Address</fullName>
            </value>
            <value>
                <fullName>Pickup Center</fullName>
                <default>true</default>
                <label>Pickup Center</label>
            </value>
            <value>
                <fullName>Venue</fullName>
                <isActive>false</isActive>
                <label>Venue</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/DeliveryGroup__c/recordTypes/Order.recordType-meta.xml
<RecordType>
    <fullName>Order</fullName>
    <active>true</active>
    <label>Order</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/BasePrice__c.field-meta.xml
<CustomField>
    <fullName>BasePrice__c</fullName>
    <label>Base Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/DeliveryGroup__c.field-meta.xml
<CustomField>
    <fullName>DeliveryGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Delivery Group and the Opportunity Product must be related to the same opportunity.</errorMessage>
        <filterItems>
            <field>$Source.OpportunityId</field>
            <operation>equals</operation>
            <valueField>DeliveryGroup__c.Opportunity__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DeliveryGroup__c</referenceTo>
    <relationshipLabel>Opportunity Products</relationshipLabel>
    <relationshipName>OpportunityProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Depth__c.field-meta.xml
<CustomField>
    <fullName>Depth__c</fullName>
    <label>Depth</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/DiscountType__c.field-meta.xml
<CustomField>
    <fullName>DiscountType__c</fullName>
    <label>Discount Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DiscountType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Height__c</fullName>
    <label>Height</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/ParentOrderProduct__c.field-meta.xml
<CustomField>
    <fullName>ParentOrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Opportunity Product</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Opportunity Products</relationshipLabel>
    <relationshipName>ChildOpportunityProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/UnitType__c.field-meta.xml
<CustomField>
    <fullName>UnitType__c</fullName>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>UnitType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Width__c.field-meta.xml
<CustomField>
    <fullName>Width__c</fullName>
    <label>Width</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DeliveryGroup__c.field-meta.xml
<CustomField>
    <fullName>DeliveryGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Delivery Group and the Order Product must be related to the same order.</errorMessage>
        <filterItems>
            <field>$Source.OrderId</field>
            <operation>equals</operation>
            <valueField>DeliveryGroup__c.Order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DeliveryGroup__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>OrderProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DeliveryType__c.field-meta.xml
<CustomField>
    <fullName>DeliveryType__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DeliveryType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DiscountAmount__c.field-meta.xml
<CustomField>
    <fullName>DiscountAmount__c</fullName>
    <description>If the discount type is &quot;Percentage,&quot; this number represents the percentage that will be deducted from the total. If the discount type is &quot;Fixed,&quot; this number represents the exact dollar amount that will be deducted from the total.</description>
    <inlineHelpText>If the discount type is &quot;Percentage,&quot; this number represents the percentage that will be deducted from the total. If the discount type is &quot;Fixed,&quot; this number represents the exact dollar amount that will be deducted from the total.</inlineHelpText>
    <label>Discount Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ParentOrderProduct__c.field-meta.xml
<CustomField>
    <fullName>ParentOrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>ChildOrderProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/WorkOrderStatus__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderStatus__c</fullName>
    <label>Work Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/DeliveryType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Delivery</fullName>
        <default>true</default>
        <label>Delivery</label>
    </customValue>
    <customValue>
        <fullName>Installation</fullName>
    </customValue>
    <customValue>
        <fullName>FedEx</fullName>
    </customValue>
    <customValue>
        <fullName>UPS</fullName>
    </customValue>
    <customValue>
        <fullName>DHL</fullName>
    </customValue>
    <customValue>
        <fullName>Courier</fullName>
    </customValue>
    <customValue>
        <fullName>Uber</fullName>
    </customValue>
    <customValue>
        <fullName>Pick Up</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Delivery Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/DiscountType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Fixed Amount</fullName>
    </customValue>
    <customValue>
        <fullName>Percentage</fullName>
    </customValue>
    <description>A &quot;percentage discount&quot; means a deduction from the original price based on a specific percentage, while a &quot;fixed amount discount&quot; refers to subtracting a set dollar amount from the original price, regardless of the item&apos;s cost; essentially, a percentage d</description>
    <masterLabel>Discount Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/UnitType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Each</fullName>
    </customValue>
    <customValue>
        <fullName>SqFt</fullName>
    </customValue>
    <customValue>
        <fullName>Hour</fullName>
    </customValue>
    <masterLabel>Unit Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OrderProductManagerCtrl.cls
/**
 * Controller for orderProductManager LWC
 * @author Fernando Gomez
 * @version 1.0 5/15/2023
 */
public with sharing class OrderProductManagerCtrl {

	/**
	 * @param orderId
	 * @return List<DeliveryGroup__c>
	 */
	@AuraEnabled(cacheable=false)
	public static List<DeliveryGroup__c> getDeliveryGroups(Id orderId) {
		try {
			return DeliveryGroupManager.getDeliveryGroups(
				new List<Id> { orderId }).get(orderId);
		} catch (Exception ex) {
			throw new AuraHandledException(ex.getMessage());
		}
	}

	/**
	 * @param orderProductId
	 * @return OrderItem
	 */
	@AuraEnabled
	public static OrderItem getSingleOrderProduct(Id orderProductId) {
		try {
			return [
				SELECT OrderItemNumber,
					AvailableQuantity,
					BasePrice__c,
					CreatedDate,
					DeliveryType__c,
					Width__c,
					Height__c,
					Depth__c,
					Description,
					DiscountType__c,
					DiscountAmount__c,
					EndDate,
					ListPrice,
					Notes__c,
					Quantity,
					TotalPrice,
					UnitPrice,
					UnitType__c,
					WorkOrderStatus__c,
					DeliveryGroup__c,
					DeliveryGroup__r.Name,
					DeliveryGroup__r.DueDate__c,
					OrderId,
					Order.DueDate__c,
					PricebookEntryId,
					ParentOrderProduct__c,
					ParentOrderProduct__r.Product2.Name,
					Product2Id,
					Product2.Name,
					Product2.ProductCode,
					Product2.Material__c,
					Product2.Material__r.Name,
					Product2.RecordTypeId,
					Product2.RecordType.DeveloperName
				FROM OrderItem
				WHERE Id = :orderProductId
			];
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
	}
	
	/**
	 * @param orderIds
	 * @return Map<Id, List<DeliveryGroup__c>>
	 */
	@AuraEnabled
	public static List<OrderItem> getOrderProductsByProductType(
		Id orderId,
		String productTypeName
	) {
		try {
			return [
				SELECT OrderItemNumber,
					AvailableQuantity,
					BasePrice__c,
					CreatedDate,
					DeliveryType__c,
					Width__c,
					Height__c,
					Depth__c,
					Description,
					DiscountType__c,
					DiscountAmount__c,
					EndDate,
					ListPrice,
					Notes__c,
					Quantity,
					TotalPrice,
					UnitPrice,
					UnitType__c,
					WorkOrderStatus__c,
					DeliveryGroup__c,
					DeliveryGroup__r.Name,
					DeliveryGroup__r.DueDate__c,
					OrderId,
					Order.DueDate__c,
					PricebookEntryId,
					ParentOrderProduct__c,
					ParentOrderProduct__r.Product2.Name,
					Product2Id,
					Product2.Name,
					Product2.ProductCode,
					Product2.Material__c,
					Product2.Material__r.Name,
					Product2.RecordTypeId,
					Product2.RecordType.DeveloperName
				FROM OrderItem
				WHERE OrderId = :orderId
				AND Product2.RecordType.DeveloperName = :productTypeName
				ORDER BY DeliveryGroup__r.DueDate__c NULLS LAST,
					DeliveryGroup__r.CreatedDate,
					CreatedDate
			];
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
	}
	
	/**
	 * @param itemsToUpsert
	 * @param itemsToDelete
	 */
	@AuraEnabled
	public static List<OrderItem> saveOrderProducts(
		List<OrderItem> itemsToUpsert,
		List<Id> itemsToDelete
	) {
		Map<Id, Id> pbeIds;
		List<Id> productIds;
		List<OrderItem> newItems;

		try {
			newItems = new List<OrderItem>();
			productIds = new List<Id>();

			// next block only if there are items to upsert
			if (!itemsToUpsert.isEmpty()) {
				for (OrderItem oi : itemsToUpsert) {
					if (String.isBlank(oi.Id)) {
						newItems.add(oi);
						productIds.add(oi.Product2Id);
					}
				}

				if (!newItems.isEmpty()) {
					pbeIds = getStandardPricebookEntryIds(productIds);
					// we have to go back and set it
					for (OrderItem oi : newItems) {
						oi.PriceBookEntryId = pbeIds.get(oi.Product2Id);
					}
				}

				upsert itemsToUpsert;
			}

			// next block only if there items to delete
			if (!itemsToDelete.isEmpty()) {
				delete [SELECT Id FROM OrderItem WHERE Id IN :itemsToDelete];
			}

			return [
				SELECT OrderItemNumber,
					AvailableQuantity,
					BasePrice__c,
					CreatedDate,
					DeliveryType__c,
					Width__c,
					Height__c,
					Depth__c,
					Description,
					DiscountType__c,
					DiscountAmount__c,
					EndDate,
					ListPrice,
					Notes__c,
					Quantity,
					TotalPrice,
					UnitPrice,
					UnitType__c,
					WorkOrderStatus__c,
					DeliveryGroup__c,
					DeliveryGroup__r.Name,
					DeliveryGroup__r.DueDate__c,
					OrderId,
					Order.DueDate__c,
					PricebookEntryId,
					ParentOrderProduct__c,
					ParentOrderProduct__r.Product2.Name,
					Product2Id,
					Product2.Name,
					Product2.ProductCode,
					Product2.Material__c,
					Product2.Material__r.Name,
					Product2.RecordTypeId,
					Product2.RecordType.DeveloperName
				FROM OrderItem
				WHERE Id IN :itemsToUpsert
				ORDER BY CreatedDate
			];
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
	}

	/**
	 * @param productIds
	 * @return 
	 */
	@AuraEnabled(cacheable=false)
	public static List<DeliveryGroup__c> getOpportunityDeliveryGroups(Id opportunityId) {
		try {
			if (opportunityId == null)
				return new List<DeliveryGroup__c>();

			return [
				SELECT Id,
					Name,
					AddressLabel__c,
					DeliveryAddressHtml__c,
					PickupAddressHtml__c,
					CreatedDate,
					DueDate__c,
					DeliveryType__c,
					DeliveryLocationType__c,
					PickupLocationType__c,
					DeliveryCenter__c,
					DeliveryCenter__r.Name,
					PickupCenter__c,
					PickupCenter__r.Name,
					(
						SELECT Id,
							SortOrder,
							BasePrice__c,
							DeliveryType__c,
							CreatedDate,
							Width__c,
							Height__c,
							Depth__c,
							Description,
							DiscountType__c,
							DiscountAmount__c,
							Notes__c,
							Quantity,
							TotalPrice,
							UnitPrice,
							UnitType__c,
							WorkOrderStatus__c,
							DeliveryGroup__c,
							DeliveryGroup__r.Name,
							DeliveryGroup__r.DueDate__c,
							OpportunityId,
							PricebookEntryId,
							ParentOrderProduct__c,
							ParentOrderProduct__r.Product2.Name,
							Product2Id,
							Product2.Name,
							Product2.ProductCode,
							Product2.Material__c,
							Product2.Material__r.Name,
							Product2.RecordTypeId,
							Product2.RecordType.DeveloperName
						FROM OpportunityProducts__r
						ORDER BY CreatedDate ASC
					)
				FROM DeliveryGroup__c
				WHERE Opportunity__c = :opportunityId
				ORDER BY DueDate__c ASC NULLS LAST, CreatedDate ASC
			];
		} catch (Exception ex) {
			throw new AuraHandledException(ex.getMessage());
		}
	}

	@AuraEnabled
	public static List<OpportunityLineItem> getOpportunityProductsByProductType(
		Id opportunityId,
		String productTypeName
	) {
		try {
			if (opportunityId == null)
				return new List<OpportunityLineItem>();

			return [
				SELECT Id,
					SortOrder,
					BasePrice__c,
					DeliveryType__c,
					CreatedDate,
					Width__c,
					Height__c,
					Depth__c,
					Description,
					DiscountType__c,
					DiscountAmount__c,
					Notes__c,
					Quantity,
					TotalPrice,
					UnitPrice,
					UnitType__c,
					WorkOrderStatus__c,
					DeliveryGroup__c,
					DeliveryGroup__r.Name,
					DeliveryGroup__r.DueDate__c,
					OpportunityId,
					PricebookEntryId,
					ParentOrderProduct__c,
					ParentOrderProduct__r.Product2.Name,
					Product2Id,
					Product2.Name,
					Product2.ProductCode,
					Product2.Material__c,
					Product2.Material__r.Name,
					Product2.RecordTypeId,
					Product2.RecordType.DeveloperName
				FROM OpportunityLineItem
				WHERE OpportunityId = :opportunityId
				AND Product2.RecordType.DeveloperName = :productTypeName
				ORDER BY DeliveryGroup__r.DueDate__c NULLS LAST,
					DeliveryGroup__r.CreatedDate,
					CreatedDate
			];
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
	}

	@AuraEnabled
	public static List<OpportunityLineItem> saveOpportunityProducts(
		List<OpportunityLineItem> itemsToUpsert,
		List<Id> itemsToDelete
	) {
		try {
			if (itemsToUpsert == null)
				itemsToUpsert = new List<OpportunityLineItem>();
			if (itemsToDelete == null)
				itemsToDelete = new List<Id>();

			if (!itemsToUpsert.isEmpty()) {
				List<OpportunityLineItem> newItems = new List<OpportunityLineItem>();
				Set<Id> productIds = new Set<Id>();
				Id opportunityId;

				for (OpportunityLineItem oli : itemsToUpsert) {
					if (String.isBlank(oli.Id)) {
						newItems.add(oli);
						if (oli.OpportunityId != null)
							opportunityId = oli.OpportunityId;
						if (oli.Product2Id != null)
							productIds.add(oli.Product2Id);
					}
				}

				if (!newItems.isEmpty()) {
					Map<Id, Id> pbeIds = getPricebookEntryIdsForOpportunity(
						new List<Id>(productIds),
						opportunityId
					);

					for (OpportunityLineItem oli : newItems) {
						if (oli.Product2Id != null)
							oli.PricebookEntryId = pbeIds.get(oli.Product2Id);
						if (oli.Quantity == null)
							oli.Quantity = 1;
						if (oli.UnitPrice == null)
							oli.UnitPrice = oli.BasePrice__c == null ? 0.01 : oli.BasePrice__c;
					}
				}

				upsert itemsToUpsert;
			}

			if (!itemsToDelete.isEmpty()) {
				delete [SELECT Id FROM OpportunityLineItem WHERE Id IN :itemsToDelete];
			}

			if (itemsToUpsert.isEmpty())
				return new List<OpportunityLineItem>();

			return [
				SELECT Id,
					SortOrder,
					BasePrice__c,
					DeliveryType__c,
					CreatedDate,
					Width__c,
					Height__c,
					Depth__c,
					Description,
					DiscountType__c,
					DiscountAmount__c,
					Notes__c,
					Quantity,
					TotalPrice,
					UnitPrice,
					UnitType__c,
					WorkOrderStatus__c,
					DeliveryGroup__c,
					DeliveryGroup__r.Name,
					DeliveryGroup__r.DueDate__c,
					OpportunityId,
					PricebookEntryId,
					ParentOrderProduct__c,
					ParentOrderProduct__r.Product2.Name,
					Product2Id,
					Product2.Name,
					Product2.ProductCode,
					Product2.Material__c,
					Product2.Material__r.Name,
					Product2.RecordTypeId,
					Product2.RecordType.DeveloperName
				FROM OpportunityLineItem
				WHERE Id IN :itemsToUpsert
				ORDER BY CreatedDate
			];
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
	}

	private static Map<Id, Id> getStandardPricebookEntryIds(List<Id> productIds) {
		Map<Id, Id> result = new Map<Id, Id>();
		for (PriceBookEntry pbe : [
			SELECT Id, Product2Id
			FROM PriceBookEntry
			WHERE Product2Id IN :productIds
			AND PriceBook2.IsStandard = true
			AND PriceBook2.IsActive = true
		]) {
			result.put(pbe.Product2Id, pbe.Id);
		}

		return result;
	}

	private static Map<Id, Id> getPricebookEntryIdsForOpportunity(List<Id> productIds, Id opportunityId) {
		Map<Id, Id> result = new Map<Id, Id>();
		if (productIds == null || productIds.isEmpty())
			return result;

		Id pricebookId;
		if (opportunityId != null) {
			Opportunity opportunityRecord = [
				SELECT Pricebook2Id
				FROM Opportunity
				WHERE Id = :opportunityId
				LIMIT 1
			];
			pricebookId = opportunityRecord.Pricebook2Id;
		}

		if (pricebookId != null) {
			for (PricebookEntry pbe : [
				SELECT Id, Product2Id
				FROM PricebookEntry
				WHERE Product2Id IN :productIds
				AND Pricebook2Id = :pricebookId
				AND IsActive = true
			]) {
				result.put(pbe.Product2Id, pbe.Id);
			}
		}

		Set<Id> missingProductIds = new Set<Id>(productIds);
		missingProductIds.removeAll(result.keySet());
		if (missingProductIds.isEmpty())
			return result;

		for (PricebookEntry pbe : [
			SELECT Id, Product2Id
			FROM PricebookEntry
			WHERE Product2Id IN :missingProductIds
			AND Pricebook2.IsStandard = true
			AND Pricebook2.IsActive = true
			AND IsActive = true
		]) {
			result.put(pbe.Product2Id, pbe.Id);
		}

		return result;
	}
}