force-app/main/default/objects/DeliveryGroup__c/DeliveryGroup__c.object-meta.xml
<CustomObject>
    <label>Delivery Group</label>
    <nameField>
        <label>Delivery Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryGroup__c/fields/AddressHtml__c.field-meta.xml
<CustomField>
    <fullName>AddressHtml__c</fullName>
    <formula>IF (
  ISPICKVAL( LocationType__c, &apos;Venue&apos; ),
  DeliveryCenter__r.ShippingStreet &amp; BR() &amp;
  DeliveryCenter__r.ShippingCity &amp; &apos; &apos; &amp;
  DeliveryCenter__r.ShippingState &amp;
  IF (
    NOT(ISBLANK( DeliveryCenter__r.ShippingPostalCode )),
    &apos;, &apos; &amp; DeliveryCenter__r.ShippingPostalCode,
    &apos;&apos;
  ) &amp; BR() &amp;
  DeliveryCenter__r.ShippingCountry,
  Address__Street__s &amp; BR() &amp;
  Address__City__s &amp; &apos; &apos; &amp;
  TEXT(Address__StateCode__s) &amp;
  IF (
    NOT(ISBLANK( Address__PostalCode__s )),
    &apos;, &apos; &amp; Address__PostalCode__s,
    &apos;&apos;
  ) &amp; BR() &amp;
  TEXT(Address__CountryCode__s)
)</formula>
    <label>Address HTML</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/AddressLabel__c.field-meta.xml
<CustomField>
    <fullName>AddressLabel__c</fullName>
    <formula>IF (
  ISPICKVAL( DeliveryLocationType__c, &apos;Delivery Center&apos; ),
  DeliveryCenter__r.ShippingStreet &amp;
  IF (
    NOT(ISBLANK( DeliveryCenter__r.ShippingCity )),
    &apos;, &apos; &amp; DeliveryCenter__r.ShippingCity,
    &apos;&apos;
  )&amp;
  IF (
    NOT(ISBLANK(DeliveryCenter__r.ShippingState )),
    &apos; &apos; &amp; DeliveryCenter__r.ShippingState,
    &apos;&apos;
  ) &amp;
  IF (
    NOT(ISBLANK( DeliveryCenter__r.ShippingPostalCode )),
    &apos;, &apos; &amp; DeliveryCenter__r.ShippingPostalCode,
    &apos;&apos;
  ),
  DeliveryAddress__Street__s &amp;
  IF (
    NOT(ISBLANK( DeliveryAddress__City__s )),
    &apos;, &apos; &amp; DeliveryAddress__City__s,
    &apos;&apos;
  ) &amp;
  IF (
    NOT(ISBLANK(TEXT(DeliveryAddress__StateCode__s ))),
    &apos; &apos; &amp; TEXT(DeliveryAddress__StateCode__s),
    &apos;&apos;
  ) &amp;
  IF (
    NOT(ISBLANK( DeliveryAddress__PostalCode__s )),
    &apos;, &apos; &amp; DeliveryAddress__PostalCode__s,
    &apos;&apos;
  )
)</formula>
    <label>Address Label</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/DeliveryCenterName__c.field-meta.xml
<CustomField>
    <fullName>DeliveryCenterName__c</fullName>
    <formula>IF(
  ISPICKVAL(LocationType__c, &apos;Delivery Center&apos;),
  DeliveryCenter__r.Name,
  &apos;&apos;
)</formula>
    <label>Delivery Center Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/DeliveryType__c.field-meta.xml
<CustomField>
    <fullName>DeliveryType__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DeliveryType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Delivery Groups</relationshipLabel>
    <relationshipName>DeliveryGroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/recordTypes/Order.recordType-meta.xml
<RecordType>
    <fullName>Order</fullName>
    <active>true</active>
    <label>Order</label>
</RecordType>

force-app/main/default/objects/OrderItem/fields/DeliveryGroup__c.field-meta.xml
<CustomField>
    <fullName>DeliveryGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Delivery Group and the Order Product must be related to the same order.</errorMessage>
        <filterItems>
            <field>$Source.OrderId</field>
            <operation>equals</operation>
            <valueField>DeliveryGroup__c.Order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DeliveryGroup__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>OrderProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DeliveryType__c.field-meta.xml
<CustomField>
    <fullName>DeliveryType__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DeliveryType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PackingSlip__c/PackingSlip__c.object-meta.xml
<CustomObject>
    <label>Packing Slip</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Packing Slip #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packing Slips</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PackingSlip__c/fields/DeliveryGroup__c.field-meta.xml
<CustomField>
    <fullName>DeliveryGroup__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Delivery Group</label>
    <referenceTo>DeliveryGroup__c</referenceTo>
    <relationshipLabel>Packing Slips</relationshipLabel>
    <relationshipName>PackingSlips</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PackingSlip__c/fields/DeliveryType__c.field-meta.xml
<CustomField>
    <fullName>DeliveryType__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Delivery_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PackingSlip__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Packing Slips</relationshipLabel>
    <relationshipName>PackingSlips</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PackingSlipItem__c/PackingSlipItem__c.object-meta.xml
<CustomObject>
    <label>Packing Slip Item</label>
    <nameField>
        <displayFormat>PSI{000000}</displayFormat>
        <label>Packing Slip Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packing Slip Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PackingSlipItem__c/fields/OrderProduct__c.field-meta.xml
<CustomField>
    <fullName>OrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Packing Slip Items</relationshipLabel>
    <relationshipName>PackingSlipItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PackingSlipItem__c/fields/PackingSlip__c.field-meta.xml
<CustomField>
    <fullName>PackingSlip__c</fullName>
    <label>Packing Slip</label>
    <referenceTo>PackingSlip__c</referenceTo>
    <relationshipLabel>Packing Slip Items</relationshipLabel>
    <relationshipName>PackingSlipItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PackingSlipItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <formula>IF(ISBLANK( OrderProduct__r.Product2Id ), &quot;&quot;, HYPERLINK(&quot;/&quot; &amp; OrderProduct__r.Product2Id, OrderProduct__r.Product2.Name, &quot;_blank&quot;))</formula>
    <label>Product</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PackingSlipItem__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/DeliveryType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Delivery</fullName>
        <default>true</default>
        <label>Delivery</label>
    </customValue>
    <customValue>
        <fullName>Installation</fullName>
    </customValue>
    <customValue>
        <fullName>FedEx</fullName>
    </customValue>
    <customValue>
        <fullName>UPS</fullName>
    </customValue>
    <customValue>
        <fullName>DHL</fullName>
    </customValue>
    <customValue>
        <fullName>Courier</fullName>
    </customValue>
    <customValue>
        <fullName>Uber</fullName>
    </customValue>
    <customValue>
        <fullName>Pick Up</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Delivery Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DefaultPackingSlipDataProvider.cls
public with sharing class DefaultPackingSlipDataProvider extends IPackingSlipDataProvider {
	public static final String PROVIDER_KEY = 'SHIPMENT';
	@TestVisible private static Id testRecordId;
	@TestVisible private static PackingSlip__c testPackingSlip;
	@TestVisible private static List<PackingSlipItem__c> testPackingSlipItems;

	public override String getProviderKey() {
		return PROVIDER_KEY;
	}

	public override Boolean supports(Schema.SObjectType objectType) {
		return objectType == PackingSlip__c.SObjectType;
	}

	public override PackingSlipDataModels.DocumentData getDocumentData(
		Id recordId,
		PackingSlipDataModels.TemplateDefinition templateDefinition
	) {
		if (recordId == null)
			throw new AuraHandledException('A recordId is required to render a packing slip.');

		PackingSlip__c packingSlip = loadPackingSlip(recordId);
		List<PackingSlipItem__c> packingSlipItems = loadPackingSlipItems(recordId);

		SObject orderRecord = packingSlip.getSObject('Order__r');
		SObject deliveryGroupRecord = packingSlip.getSObject('DeliveryGroup__r');
		String orderNumber = orderRecord == null ? null : (String)orderRecord.get('OrderNumber');
		String carrier = deliveryGroupRecord == null ? null : (String)deliveryGroupRecord.get('DeliveryType__c');
		String shipToName = deliveryGroupRecord == null ? null : (String)deliveryGroupRecord.get('DeliveryCenterName__c');
		String shipToAddress = deliveryGroupRecord == null ? null : sanitizeAddress((String)deliveryGroupRecord.get('AddressHtml__c'));

		PackingSlipDataModels.DocumentData document = new PackingSlipDataModels.DocumentData();
		document.header.recordId = String.valueOf(packingSlip.Id);
		document.header.orderNumber = orderNumber;
		document.header.trackingNumber = packingSlip.TrackingNumber__c;
		document.header.carrier = carrier;
		document.header.description = packingSlip.Description__c;
		document.shipTo.name = shipToName;
		document.shipTo.address = shipToAddress;
		document.barcodeValue = packingSlip.TrackingNumber__c;
		document.qrValue = packingSlip.TrackingNumber__c;
		document.footerNotes = 'Generated from Packing Slip ' + packingSlip.Name + '.';
		document.tokenValues.put('ShipmentName', packingSlip.Name);
		document.tokenValues.put('PackingSlipName', packingSlip.Name);

		for (PackingSlipItem__c itemRecord : packingSlipItems) {
			SObject orderProductRecord = itemRecord.getSObject('OrderProduct__r');
			SObject productRecord = orderProductRecord == null ? null : orderProductRecord.getSObject('Product2');
			PackingSlipDataModels.LineItemData item = new PackingSlipDataModels.LineItemData();
			item.productCode = productRecord == null ? null : (String)productRecord.get('ProductCode');
			item.productName = productRecord == null ? itemRecord.Product__c : (String)productRecord.get('Name');
			item.quantity = itemRecord.Quantity__c;
			item.description = orderProductRecord == null ? itemRecord.Product__c : (String)orderProductRecord.get('Description');
			if (String.isBlank(item.productCode))
				item.productCode = item.productName;
			if (String.isBlank(item.productName))
				item.productName = itemRecord.Name;
			if (String.isBlank(item.description))
				item.description = item.productName;
			document.items.add(item);
		}

		return document;
	}

	private static PackingSlip__c loadPackingSlip(Id recordId) {
		if (testRecordId != null && testRecordId == recordId && testPackingSlip != null)
			return testPackingSlip;

		String query = String.join(
			new List<String>{
				'SELECT Id, Name, TrackingNumber__c, Description__c,',
				'Order__r.OrderNumber,',
				'DeliveryGroup__r.Name,',
				'DeliveryGroup__r.DeliveryCenterName__c,',
				'DeliveryGroup__r.AddressLabel__c,',
				'DeliveryGroup__r.AddressHtml__c,',
				'DeliveryGroup__r.DeliveryType__c',
				'FROM PackingSlip__c',
				'WHERE Id = :recordId',
				'LIMIT 1'
			},
			' '
		);

		return (PackingSlip__c)Database.query(query);
	}

	private static List<PackingSlipItem__c> loadPackingSlipItems(Id recordId) {
		if (testRecordId != null && testRecordId == recordId && testPackingSlipItems != null)
			return testPackingSlipItems;

		return [
			SELECT Id, Name, Product__c, Quantity__c,
				OrderProduct__r.Description,
				OrderProduct__r.Product2.Name,
				OrderProduct__r.Product2.ProductCode
			FROM PackingSlipItem__c
			WHERE PackingSlip__c = :recordId
			ORDER BY CreatedDate ASC
		];
	}

	private static String sanitizeAddress(String addressHtml) {
		if (String.isBlank(addressHtml))
			return null;

		String normalizedAddress = addressHtml.replaceAll('(?i)<br\\s*/?>', '\n');
		normalizedAddress = normalizedAddress.replaceAll('<[^>]+>', '');
		normalizedAddress = normalizedAddress.replace('&nbsp;', ' ');
		return normalizedAddress.trim();
	}

	@TestVisible
	static void setTestData(Id recordId, PackingSlip__c packingSlip, List<PackingSlipItem__c> packingSlipItems) {
		testRecordId = recordId;
		testPackingSlip = packingSlip;
		testPackingSlipItems = packingSlipItems;
	}

	@TestVisible
	static void clearTestData() {
		testRecordId = null;
		testPackingSlip = null;
		testPackingSlipItems = null;
	}
}