force-app/main/default/objects/DeliveryGroup__c/DeliveryGroup__c.object-meta.xml
<CustomObject>
    <label>Delivery Group</label>
    <nameField>
        <label>Delivery Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryGroup__c/fields/AddressHtml__c.field-meta.xml
<CustomField>
    <fullName>AddressHtml__c</fullName>
    <formula>IF (
  ISPICKVAL( LocationType__c, &apos;Venue&apos; ),
  DeliveryCenter__r.ShippingStreet &amp; BR() &amp;
  DeliveryCenter__r.ShippingCity &amp; &apos; &apos; &amp;
  DeliveryCenter__r.ShippingState &amp;
  IF (
    NOT(ISBLANK( DeliveryCenter__r.ShippingPostalCode )),
    &apos;, &apos; &amp; DeliveryCenter__r.ShippingPostalCode,
    &apos;&apos;
  ) &amp; BR() &amp;
  DeliveryCenter__r.ShippingCountry,
  Address__Street__s &amp; BR() &amp;
  Address__City__s &amp; &apos; &apos; &amp;
  TEXT(Address__StateCode__s) &amp;
  IF (
    NOT(ISBLANK( Address__PostalCode__s )),
    &apos;, &apos; &amp; Address__PostalCode__s,
    &apos;&apos;
  ) &amp; BR() &amp;
  TEXT(Address__CountryCode__s)
)</formula>
    <label>Address HTML</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/AddressLabel__c.field-meta.xml
<CustomField>
    <fullName>AddressLabel__c</fullName>
    <formula>IF (
  ISPICKVAL( DeliveryLocationType__c, &apos;Delivery Center&apos; ),
  DeliveryCenter__r.ShippingStreet &amp;
  IF (
    NOT(ISBLANK( DeliveryCenter__r.ShippingCity )),
    &apos;, &apos; &amp; DeliveryCenter__r.ShippingCity,
    &apos;&apos;
  )&amp;
  IF (
    NOT(ISBLANK(DeliveryCenter__r.ShippingState )),
    &apos; &apos; &amp; DeliveryCenter__r.ShippingState,
    &apos;&apos;
  ) &amp;
  IF (
    NOT(ISBLANK( DeliveryCenter__r.ShippingPostalCode )),
    &apos;, &apos; &amp; DeliveryCenter__r.ShippingPostalCode,
    &apos;&apos;
  ),
  DeliveryAddress__Street__s &amp;
  IF (
    NOT(ISBLANK( DeliveryAddress__City__s )),
    &apos;, &apos; &amp; DeliveryAddress__City__s,
    &apos;&apos;
  ) &amp;
  IF (
    NOT(ISBLANK(TEXT(DeliveryAddress__StateCode__s ))),
    &apos; &apos; &amp; TEXT(DeliveryAddress__StateCode__s),
    &apos;&apos;
  ) &amp;
  IF (
    NOT(ISBLANK( DeliveryAddress__PostalCode__s )),
    &apos;, &apos; &amp; DeliveryAddress__PostalCode__s,
    &apos;&apos;
  )
)</formula>
    <label>Address Label</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/DeliveryCenter__c.field-meta.xml
<CustomField>
    <fullName>DeliveryCenter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Center</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Delivery Groups</relationshipLabel>
    <relationshipName>DeliveryCenter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/DeliveryType__c.field-meta.xml
<CustomField>
    <fullName>DeliveryType__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DeliveryType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/LocationType__c.field-meta.xml
<CustomField>
    <fullName>LocationType__c</fullName>
    <label>Location Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Address</fullName>
            </value>
            <value>
                <fullName>Delivery Center</fullName>
                <default>true</default>
                <label>Delivery Center</label>
            </value>
            <value>
                <fullName>Venue</fullName>
                <isActive>false</isActive>
                <label>Venue</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Delivery Groups</relationshipLabel>
    <relationshipName>DeliveryGroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/recordTypes/Order.recordType-meta.xml
<RecordType>
    <fullName>Order</fullName>
    <active>true</active>
    <label>Order</label>
</RecordType>

force-app/main/default/objects/OrderItem/fields/DeliveryGroup__c.field-meta.xml
<CustomField>
    <fullName>DeliveryGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Delivery Group and the Order Product must be related to the same order.</errorMessage>
        <filterItems>
            <field>$Source.OrderId</field>
            <operation>equals</operation>
            <valueField>DeliveryGroup__c.Order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DeliveryGroup__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>OrderProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DeliveryType__c.field-meta.xml
<CustomField>
    <fullName>DeliveryType__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DeliveryType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DiscountAmount__c.field-meta.xml
<CustomField>
    <fullName>DiscountAmount__c</fullName>
    <description>If the discount type is &quot;Percentage,&quot; this number represents the percentage that will be deducted from the total. If the discount type is &quot;Fixed,&quot; this number represents the exact dollar amount that will be deducted from the total.</description>
    <inlineHelpText>If the discount type is &quot;Percentage,&quot; this number represents the percentage that will be deducted from the total. If the discount type is &quot;Fixed,&quot; this number represents the exact dollar amount that will be deducted from the total.</inlineHelpText>
    <label>Discount Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ParentOrderProduct__c.field-meta.xml
<CustomField>
    <fullName>ParentOrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>ChildOrderProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/WorkOrderStatus__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderStatus__c</fullName>
    <label>Work Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItemWorkOrder__c/OrderItemWorkOrder__c.object-meta.xml
<CustomObject>
    <label>Order Product Work Order</label>
    <nameField>
        <displayFormat>OIWO{000000}</displayFormat>
        <label>Order Item Work Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Products Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItemWorkOrder__c/fields/OrderItem__c.field-meta.xml
<CustomField>
    <fullName>OrderItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Order Products Work Orders</relationshipLabel>
    <relationshipName>OrderItemsWorkOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItemWorkOrder__c/fields/WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>WorkOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipName>OrderItemsWorkOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItemWorkOrder__c/fields/WorkOrderStatus__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderStatus__c</fullName>
    <formula>TEXT( WorkOrder__r.Status )</formula>
    <label>Work Order Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PackingSlip__c/PackingSlip__c.object-meta.xml
<CustomObject>
    <label>Packing Slip</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Packing Slip #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packing Slips</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PackingSlip__c/fields/DeliveryGroup__c.field-meta.xml
<CustomField>
    <fullName>DeliveryGroup__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Delivery Group</label>
    <referenceTo>DeliveryGroup__c</referenceTo>
    <relationshipLabel>Packing Slips</relationshipLabel>
    <relationshipName>PackingSlips</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PackingSlip__c/fields/DeliveryType__c.field-meta.xml
<CustomField>
    <fullName>DeliveryType__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Delivery_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PackingSlip__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Packing Slips</relationshipLabel>
    <relationshipName>PackingSlips</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Finish__c.field-meta.xml
<CustomField>
    <fullName>Finish__c</fullName>
    <label>Finish</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Finishing</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/DeliveryType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Delivery</fullName>
        <default>true</default>
        <label>Delivery</label>
    </customValue>
    <customValue>
        <fullName>Installation</fullName>
    </customValue>
    <customValue>
        <fullName>FedEx</fullName>
    </customValue>
    <customValue>
        <fullName>UPS</fullName>
    </customValue>
    <customValue>
        <fullName>DHL</fullName>
    </customValue>
    <customValue>
        <fullName>Courier</fullName>
    </customValue>
    <customValue>
        <fullName>Uber</fullName>
    </customValue>
    <customValue>
        <fullName>Pick Up</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Delivery Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Finishing.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
        <default>true</default>
        <label>Standard</label>
    </customValue>
    <customValue>
        <fullName>Deluxe</fullName>
    </customValue>
    <customValue>
        <fullName>Matte</fullName>
    </customValue>
    <customValue>
        <fullName>Gloss</fullName>
    </customValue>
    <customValue>
        <fullName>Semi-Gloss</fullName>
    </customValue>
    <customValue>
        <fullName>Dry Erase</fullName>
    </customValue>
    <customValue>
        <fullName>Double Sided</fullName>
    </customValue>
    <customValue>
        <fullName>UV Coating</fullName>
    </customValue>
    <customValue>
        <fullName>No Coating</fullName>
    </customValue>
    <customValue>
        <fullName>Spot UV in both sides</fullName>
    </customValue>
    <customValue>
        <fullName>Spot UV on one side</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Finishing</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DeliveryGroupManager.cls
/**
 * Common read/write method involving the Delivery Group object.
 * @author Fernando Gomez
 * @version 1.0 9/15/2024
 */
public with sharing class DeliveryGroupManager {
	/* public DeliveryGroupManager() {

	} */

	/**
	 * @param orderIds
	 * @return Map<Id, List<DeliveryGroup__c>>
	 */
	public static Map<Id, List<DeliveryGroup__c>> getDeliveryGroups(List<Id> orderIds) {
		List<DeliveryGroup__c> groups;
		Map<Id, List<DeliveryGroup__c>> result =
			new Map<Id, List<DeliveryGroup__c>>();

		for (Id orderId : orderIds){
			result.put(orderId, new List<DeliveryGroup__c>());
		}

		groups = [
			SELECT Name,
				AddressLabel__c,
				AddressHtml__c,
				Address__City__s,
				Address__CountryCode__s,
				Address__GeocodeAccuracy__s,
				Address__Latitude__s,
				Address__Longitude__s,
				Address__PostalCode__s,
				Address__StateCode__s,
				Address__Street__s,
				DueDate__c,
				DeliveryType__c,
				LocationType__c,
				Order__c,
				DeliveryCenter__c,
				DeliveryCenter__r.Name,
				(
					SELECT Name,
						Description__c,
						TrackingNumber__c
					FROM PackingSlips__r
					ORDER BY Name
				),
				(
					SELECT AvailableQuantity,
						BasePrice__c,
						CreatedDate,
						DeliveryGroup__c,
						DeliveryType__c,
						Width__c,
						Height__c,
						Depth__c,
						Description,
						DiscountType__c,
						DiscountAmount__c,
						EndDate,
						ListPrice,
						Notes__c,
						Quantity,
						TotalPrice,
						UnitPrice,
						UnitType__c,
						WorkOrderStatus__c,
						OrderId,
						PricebookEntryId,
						ParentOrderProduct__c,
						ParentOrderProduct__r.Product2.Name,
						Product2Id,
						Product2.Name,
						Product2.ProductCode,
						Product2.Finish__c,
						Product2.Material__c,
						Product2.Material__r.Name,
						Product2.RecordTypeId,
						Product2.RecordType.DeveloperName
					FROM OrderProducts__r
					ORDER BY CreatedDate
				)
			FROM DeliveryGroup__c
			WHERE Order__c = :orderIds
			ORDER BY DueDate__c NULLS LAST, CreatedDate
		];

		for (DeliveryGroup__c g : groups) {
			result.get(g.Order__c).add(g);
		}

		return result;
	}

	/**
	 * Returns delivery groups (with their order products) for the specified Order Id.
	 * @param orderId Id of the order
	 * @return List<DeliveryGroup__c>
	 */
	@AuraEnabled(cacheable=true)
	public static List<DeliveryGroup__c> getDeliveryGroupsByOrder(Id orderId) {
		try {
			if (orderId == null) {
				return new List<DeliveryGroup__c>();
			}

			return getDeliveryGroups(new List<Id> { orderId }).get(orderId);
		} catch (Exception ex) {
			throw new AuraHandledException(ex.getMessage());
		}
	}


	/**
	 * Returns delivery groups (with their order products) that contain order items
	 * linked to the specified Work Order Id.
	 * @param workOrderId Id of the work order
	 * @return List<DeliveryGroup__c> with OrderProducts__r filtered to the work order
	 */
	@AuraEnabled(cacheable=true)
	public static List<DeliveryGroup__c> getDeliveryGroupsByWorkOrder(Id workOrderId) {
		try {
			if (workOrderId == null) {
				return new List<DeliveryGroup__c>();
			}
			// get linking records to determine delivery groups 
			// and order items to include
			List<OrderItemWorkOrder__c> links = [
				SELECT OrderItem__c, OrderItem__r.DeliveryGroup__c
				FROM OrderItemWorkOrder__c
				WHERE WorkOrder__c = :workOrderId
			];

			if (links.isEmpty()) {
				return new List<DeliveryGroup__c>();
			}

			Set<Id> deliveryGroupIds = new Set<Id>();
			Set<Id> orderItemIds = new Set<Id>();
			for (OrderItemWorkOrder__c l : links) {
				if (l.OrderItem__r.DeliveryGroup__c != null) {
					deliveryGroupIds.add(l.OrderItem__r.DeliveryGroup__c);
				}

				if (l.OrderItem__c != null) {
					orderItemIds.add(l.OrderItem__c);
				}
			}

			if (deliveryGroupIds.isEmpty()) {
				return new List<DeliveryGroup__c>();
			}

			List<DeliveryGroup__c> groups = [
				SELECT Name,
					AddressLabel__c,
					AddressHtml__c,
					Address__City__s,
					Address__CountryCode__s,
					Address__GeocodeAccuracy__s,
					Address__Latitude__s,
					Address__Longitude__s,
					Address__PostalCode__s,
					Address__StateCode__s,
					Address__Street__s,
					DueDate__c,
					DeliveryType__c,
					LocationType__c,
					Order__c,
					DeliveryCenter__c,
					DeliveryCenter__r.Name,
					(
						SELECT Name,
							Description__c,
							TrackingNumber__c
						FROM PackingSlips__r
						ORDER BY Name
					),
					(
						SELECT AvailableQuantity,
							BasePrice__c,
							CreatedDate,
							DeliveryGroup__c,
							DeliveryType__c,
							Width__c,
							Height__c,
							Depth__c,
							Description,
							DiscountType__c,
							DiscountAmount__c,
							EndDate,
							ListPrice,
							Notes__c,
							Quantity,
							TotalPrice,
							UnitPrice,
							UnitType__c,
							WorkOrderStatus__c,
							OrderId,
							PricebookEntryId,
							ParentOrderProduct__c,
							ParentOrderProduct__r.Product2.Name,
							Product2Id,
							Product2.Name,
							Product2.ProductCode,
							Product2.Finish__c,
							Product2.Material__c,
							Product2.Material__r.Name,
							Product2.RecordTypeId,
							Product2.RecordType.DeveloperName
						FROM OrderProducts__r
						WHERE Id IN :orderItemIds
						ORDER BY CreatedDate
					)
				FROM DeliveryGroup__c
				WHERE Id IN :deliveryGroupIds
				ORDER BY DueDate__c NULLS LAST, CreatedDate
			];
			return groups;
		} catch (Exception ex) {
			throw new AuraHandledException(ex.getMessage());
		}
	}

	/**
	 * @param newOrders
	 * @param sourceOrders
	 */
	public static void clone(List<Order> newOrders, List<Order> sourceOrders) {
		List<DeliveryGroup__c> sourceGroups;
		DeliveryGroup__c sourceGroup;
		DeliveryGroup__c targetGroup;
		Order newOrder;
		Order sourceOrder;

		Map<Id, Order> sourceOrdersMap = new Map<Id, Order>(sourceOrders);
		Map<Id, Order> newOrdersBySourceIdMap = new Map<Id, Order>();
		List<OrderItem> newOrderedProducts = new List<OrderItem>();
		Map<Id, DeliveryGroup__c> sourceGroupBySourceId =
			new Map<Id, DeliveryGroup__c>();
		Map<Id, DeliveryGroup__c> targetGroupBySourceId =
			new Map<Id, DeliveryGroup__c>();
		Map<Id, List<OrderItem>> newOrderProductsBySourceIdMap =
			new Map<Id, List<OrderItem>>();

		// we link new order to source orders in the map
		for (Integer i = 0; i < newOrders.size(); i++) {
			newOrder = newOrders[i];
			sourceOrder = sourceOrders[i];
			newOrdersBySourceIdMap.put(sourceOrder.Id, newOrder);
		}

		sourceGroups = [
			SELECT Name,
				Address__City__s,
				Address__CountryCode__s,
				Address__GeocodeAccuracy__s,
				Address__Latitude__s,
				Address__Longitude__s,
				Address__PostalCode__s,
				Address__StateCode__s,
				Address__Street__s,
				DueDate__c,
				DeliveryType__c,
				LocationType__c,
				Order__c,
				DeliveryCenter__c,
				(
					SELECT Name,
						Description__c,
						TrackingNumber__c
					FROM PackingSlips__r
					ORDER BY Name
				),
				(
					SELECT AvailableQuantity,
						BasePrice__c,
						DeliveryGroup__c,
						DeliveryType__c,
						Width__c,
						Height__c,
						Depth__c,
						Description,
						EndDate,
						ListPrice,
						Notes__c,
						Quantity,
						TotalPrice,
						UnitPrice,
						UnitType__c,
						OrderId,
						ParentOrderProduct__c,
						PricebookEntryId,
						Product2Id
					FROM OrderProducts__r
					ORDER BY CreatedDate
				)
			FROM DeliveryGroup__c
			WHERE Order__c IN :sourceOrdersMap.keySet()
		];

		// we clone all delivery groups
		for (DeliveryGroup__c sg : sourceGroups) {
			newOrder = newOrdersBySourceIdMap.get(sg.Order__c);
			sourceOrder = sourceOrdersMap.get(sg.Order__c);
			targetGroup = sg.clone(false, true, false, false);
			// fields to modify
			targetGroup.Order__c = newOrder.Id;
			sourceGroupBySourceId.put(sg.Id, sg);
			targetGroupBySourceId.put(sg.Id, targetGroup);
			// we clone the products as well
			// and we map the products to find them after insert
			newOrderProductsBySourceIdMap.put(
				sg.Id,
				sg.OrderProducts__r.deepClone(false, false, false));
		}

		// targetGroups
		insert targetGroupBySourceId.values();

		// we then fix the ids of the new order products
		for (Id sourceId : targetGroupBySourceId.keySet()) {
			sourceGroup = sourceGroupBySourceId.get(sourceId);
			targetGroup = targetGroupBySourceId.get(sourceId);

			for (OrderItem item : newOrderProductsBySourceIdMap.get(sourceId)) {
				item.DeliveryGroup__c = targetGroup.Id;
				item.OrderId = targetGroup.Order__c;
				newOrderedProducts.add(item);
			}
		}

		insert newOrderedProducts;
	}

	@AuraEnabled
	public static Id clone(Id deliveryGroupId, String newName) {
		DeliveryGroup__c sourceGroup;
		DeliveryGroup__c targetGroup;
		List<OrderItem> newOrderProducts;
		OrderItem targetOrderProduct;

		try {
			sourceGroup = [
				SELECT Address__City__s,
					Address__CountryCode__s,
					Address__GeocodeAccuracy__s,
					Address__Latitude__s,
					Address__Longitude__s,
					Address__PostalCode__s,
					Address__StateCode__s,
					Address__Street__s,
					DueDate__c,
					DeliveryType__c,
					LocationType__c,
					Order__c,
					DeliveryCenter__c,
					(
						SELECT Name,
							Description__c,
							TrackingNumber__c
						FROM PackingSlips__r
						ORDER BY Name
					),
					(
						SELECT AvailableQuantity,
							BasePrice__c,
							DeliveryGroup__c,
							DeliveryType__c,
							Width__c,
							Height__c,
							Depth__c,
							Description,
							EndDate,
							ListPrice,
							Notes__c,
							OrderId,
							ParentOrderProduct__c,
							PricebookEntryId,
							Product2Id,
							Quantity,
							TotalPrice,
							UnitPrice,
							UnitType__c
						FROM OrderProducts__r
						ORDER BY CreatedDate
					)
				FROM DeliveryGroup__c
				WHERE Id = :deliveryGroupId
			];

			targetGroup = sourceGroup.clone(false, true, false, false);
			targetGroup.Name = newName;
			insert targetGroup;

			if (!sourceGroup.OrderProducts__r.isEmpty()) {
				newOrderProducts = new List<OrderItem>();

				for (OrderItem sourceOrderProduct : sourceGroup.OrderProducts__r) {
					targetOrderProduct =
						sourceOrderProduct.clone(false, true, false, false);
					targetOrderProduct.DeliveryGroup__c = targetGroup.Id;
					newOrderProducts.add(targetOrderProduct);
				}

				insert newOrderProducts;
			}

			return targetGroup.Id;
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
	}
}