force-app/main/default/objects/DeliveryGroup__c/DeliveryGroup__c.object-meta.xml
<CustomObject>
    <label>Delivery Group</label>
    <nameField>
        <label>Delivery Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryGroup__c/fields/AddressLabel__c.field-meta.xml
<CustomField>
    <fullName>AddressLabel__c</fullName>
    <formula>IF (
  ISPICKVAL( DeliveryLocationType__c, &apos;Delivery Center&apos; ),
  DeliveryCenter__r.ShippingStreet &amp;
  IF (
    NOT(ISBLANK( DeliveryCenter__r.ShippingCity )),
    &apos;, &apos; &amp; DeliveryCenter__r.ShippingCity,
    &apos;&apos;
  )&amp;
  IF (
    NOT(ISBLANK(DeliveryCenter__r.ShippingState )),
    &apos; &apos; &amp; DeliveryCenter__r.ShippingState,
    &apos;&apos;
  ) &amp;
  IF (
    NOT(ISBLANK( DeliveryCenter__r.ShippingPostalCode )),
    &apos;, &apos; &amp; DeliveryCenter__r.ShippingPostalCode,
    &apos;&apos;
  ),
  DeliveryAddress__Street__s &amp;
  IF (
    NOT(ISBLANK( DeliveryAddress__City__s )),
    &apos;, &apos; &amp; DeliveryAddress__City__s,
    &apos;&apos;
  ) &amp;
  IF (
    NOT(ISBLANK(TEXT(DeliveryAddress__StateCode__s ))),
    &apos; &apos; &amp; TEXT(DeliveryAddress__StateCode__s),
    &apos;&apos;
  ) &amp;
  IF (
    NOT(ISBLANK( DeliveryAddress__PostalCode__s )),
    &apos;, &apos; &amp; DeliveryAddress__PostalCode__s,
    &apos;&apos;
  )
)</formula>
    <label>Address Label</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/DeliveryAddressHtml__c.field-meta.xml
<CustomField>
    <fullName>DeliveryAddressHtml__c</fullName>
    <formula>IF (
  ISPICKVAL( DeliveryLocationType__c, &apos;Delivery Center&apos; ),
  DeliveryCenter__r.ShippingStreet &amp; " " &amp;
  DeliveryCenter__r.ShippingCity &amp; &apos; &apos; &amp;
  DeliveryCenter__r.ShippingState &amp;
  IF (
    NOT(ISBLANK( DeliveryCenter__r.ShippingPostalCode )),
    &apos;, &apos; &amp; DeliveryCenter__r.ShippingPostalCode,
    &apos;&apos;
  ) &amp; " " &amp;
  DeliveryCenter__r.ShippingCountry,
  DeliveryAddress__Street__s &amp; " " &amp;
  DeliveryAddress__City__s &amp; &apos; &apos; &amp;
  TEXT(DeliveryAddress__StateCode__s) &amp;
  IF (
    NOT(ISBLANK( DeliveryAddress__PostalCode__s )),
    &apos;, &apos; &amp; DeliveryAddress__PostalCode__s,
    &apos;&apos;
  ) &amp; " " &amp;
  TEXT(DeliveryAddress__CountryCode__s)
)</formula>
    <label>Delivery Address HTML</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/DeliveryCenter__c.field-meta.xml
<CustomField>
    <fullName>DeliveryCenter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Center</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Delivery Groups</relationshipLabel>
    <relationshipName>DeliveryCenter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/DeliveryLocationType__c.field-meta.xml
<CustomField>
    <fullName>DeliveryLocationType__c</fullName>
    <label>Location Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Address</fullName>
            </value>
            <value>
                <fullName>Delivery Center</fullName>
                <default>true</default>
                <label>Delivery Center</label>
            </value>
            <value>
                <fullName>Venue</fullName>
                <isActive>false</isActive>
                <label>Venue</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/DeliveryType__c.field-meta.xml
<CustomField>
    <fullName>DeliveryType__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DeliveryType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Delivery Groups</relationshipLabel>
    <relationshipName>DeliveryGroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Delivery Groups</relationshipLabel>
    <relationshipName>DeliveryGroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/PickupAddressHtml__c.field-meta.xml
<CustomField>
    <fullName>PickupAddressHtml__c</fullName>
    <formula>IF (
  ISPICKVAL( PickupLocationType__c, &apos;Pickup Center&apos; ),
  PickupCenter__r.ShippingStreet &amp; " " &amp;
  PickupCenter__r.ShippingCity &amp; &apos; &apos; &amp;
  PickupCenter__r.ShippingState &amp;
  IF (
    NOT(ISBLANK( PickupCenter__r.ShippingPostalCode )),
    &apos;, &apos; &amp; PickupCenter__r.ShippingPostalCode,
    &apos;&apos;
  ) &amp; " " &amp;
  PickupCenter__r.ShippingCountry,
  PickupAddress__Street__s &amp; " " &amp;
  PickupAddress__City__s &amp; &apos; &apos; &amp;
  TEXT(PickupAddress__StateCode__s) &amp;
  IF (
    NOT(ISBLANK( PickupAddress__PostalCode__s )),
    &apos;, &apos; &amp; PickupAddress__PostalCode__s,
    &apos;&apos;
  ) &amp; " " &amp;
  TEXT(PickupAddress__CountryCode__s)
)</formula>
    <label>Pickup Address HTML</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/PickupCenter__c.field-meta.xml
<CustomField>
    <fullName>PickupCenter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pickup Center</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Delivery Groups</relationshipLabel>
    <relationshipName>PickupCenter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/fields/PickupLocationType__c.field-meta.xml
<CustomField>
    <fullName>PickupLocationType__c</fullName>
    <label>Pickup Location Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Address</fullName>
            </value>
            <value>
                <fullName>Pickup Center</fullName>
                <default>true</default>
                <label>Pickup Center</label>
            </value>
            <value>
                <fullName>Venue</fullName>
                <isActive>false</isActive>
                <label>Venue</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryGroup__c/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/DeliveryGroup__c/recordTypes/Order.recordType-meta.xml
<RecordType>
    <fullName>Order</fullName>
    <active>true</active>
    <label>Order</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/BasePrice__c.field-meta.xml
<CustomField>
    <fullName>BasePrice__c</fullName>
    <label>Base Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/DeliveryGroup__c.field-meta.xml
<CustomField>
    <fullName>DeliveryGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Delivery Group and the Opportunity Product must be related to the same opportunity.</errorMessage>
        <filterItems>
            <field>$Source.OpportunityId</field>
            <operation>equals</operation>
            <valueField>DeliveryGroup__c.Opportunity__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DeliveryGroup__c</referenceTo>
    <relationshipLabel>Opportunity Products</relationshipLabel>
    <relationshipName>OpportunityProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Depth__c.field-meta.xml
<CustomField>
    <fullName>Depth__c</fullName>
    <label>Depth</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/DiscountType__c.field-meta.xml
<CustomField>
    <fullName>DiscountType__c</fullName>
    <label>Discount Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DiscountType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Height__c</fullName>
    <label>Height</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/ParentOrderProduct__c.field-meta.xml
<CustomField>
    <fullName>ParentOrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Opportunity Product</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Opportunity Products</relationshipLabel>
    <relationshipName>ChildOpportunityProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/UnitType__c.field-meta.xml
<CustomField>
    <fullName>UnitType__c</fullName>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>UnitType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Width__c.field-meta.xml
<CustomField>
    <fullName>Width__c</fullName>
    <label>Width</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DeliveryGroup__c.field-meta.xml
<CustomField>
    <fullName>DeliveryGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Delivery Group and the Order Product must be related to the same order.</errorMessage>
        <filterItems>
            <field>$Source.OrderId</field>
            <operation>equals</operation>
            <valueField>DeliveryGroup__c.Order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DeliveryGroup__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>OrderProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DeliveryType__c.field-meta.xml
<CustomField>
    <fullName>DeliveryType__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DeliveryType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DiscountAmount__c.field-meta.xml
<CustomField>
    <fullName>DiscountAmount__c</fullName>
    <description>If the discount type is &quot;Percentage,&quot; this number represents the percentage that will be deducted from the total. If the discount type is &quot;Fixed,&quot; this number represents the exact dollar amount that will be deducted from the total.</description>
    <inlineHelpText>If the discount type is &quot;Percentage,&quot; this number represents the percentage that will be deducted from the total. If the discount type is &quot;Fixed,&quot; this number represents the exact dollar amount that will be deducted from the total.</inlineHelpText>
    <label>Discount Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ParentOrderProduct__c.field-meta.xml
<CustomField>
    <fullName>ParentOrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>ChildOrderProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/WorkOrderStatus__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderStatus__c</fullName>
    <label>Work Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/DeliveryType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Delivery</fullName>
        <default>true</default>
        <label>Delivery</label>
    </customValue>
    <customValue>
        <fullName>Installation</fullName>
    </customValue>
    <customValue>
        <fullName>FedEx</fullName>
    </customValue>
    <customValue>
        <fullName>UPS</fullName>
    </customValue>
    <customValue>
        <fullName>DHL</fullName>
    </customValue>
    <customValue>
        <fullName>Courier</fullName>
    </customValue>
    <customValue>
        <fullName>Uber</fullName>
    </customValue>
    <customValue>
        <fullName>Pick Up</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Delivery Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/DiscountType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Fixed Amount</fullName>
    </customValue>
    <customValue>
        <fullName>Percentage</fullName>
    </customValue>
    <description>A &quot;percentage discount&quot; means a deduction from the original price based on a specific percentage, while a &quot;fixed amount discount&quot; refers to subtracting a set dollar amount from the original price, regardless of the item&apos;s cost; essentially, a percentage d</description>
    <masterLabel>Discount Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/UnitType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Each</fullName>
    </customValue>
    <customValue>
        <fullName>SqFt</fullName>
    </customValue>
    <customValue>
        <fullName>Hour</fullName>
    </customValue>
    <masterLabel>Unit Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OpportunityOrderService.cls
/**
 * Reusable bulkified service to create Orders from Opportunities.
 */
public with sharing class OpportunityOrderService {

	public class Result {
		public Id opportunityId;
		public Id orderId;
		public Boolean success;
		public String message;
	}

	public static List<Result> createOrdersFromOpportunities(Set<Id> opportunityIds) {
		if (opportunityIds == null || opportunityIds.isEmpty()) {
			return new List<Result>();
		}

		Map<Id, Opportunity> opportunitiesById = new Map<Id, Opportunity>([
			SELECT Id, AccountId, Pricebook2Id, CloseDate
			FROM Opportunity
			WHERE Id IN :opportunityIds
		]);

		Map<Id, Order> existingOrderByOpportunityId = new Map<Id, Order>();
		for (Order orderRecord : [
			SELECT Id, OpportunityId
			FROM Order
			WHERE OpportunityId IN :opportunityIds
		]) {
			if (!existingOrderByOpportunityId.containsKey(orderRecord.OpportunityId)) {
				existingOrderByOpportunityId.put(orderRecord.OpportunityId, orderRecord);
			}
		}

		List<Order> ordersToInsert = new List<Order>();
		List<Id> orderOpportunitySequence = new List<Id>();
		Map<Id, Result> resultByOpportunityId = new Map<Id, Result>();
		Map<Id, Id> newOrderIdByOpportunityId = new Map<Id, Id>();

		for (Id opportunityId : opportunityIds) {
			Result result = new Result();
			result.opportunityId = opportunityId;
			result.success = false;

			Opportunity opp = opportunitiesById.get(opportunityId);
			if (opp == null) {
				result.message = 'Opportunity not found.';
				resultByOpportunityId.put(opportunityId, result);
				continue;
			}

			if (existingOrderByOpportunityId.containsKey(opportunityId)) {
				result.orderId = existingOrderByOpportunityId.get(opportunityId).Id;
				result.success = true;
				result.message = 'Order already exists for this Opportunity.';
				resultByOpportunityId.put(opportunityId, result);
				continue;
			}

			if (opp.AccountId == null) {
				result.message = 'Opportunity must have an Account to create an Order.';
				resultByOpportunityId.put(opportunityId, result);
				continue;
			}

			Order orderToCreate = new Order();
			orderToCreate.AccountId = opp.AccountId;
			orderToCreate.OpportunityId = opp.Id;
			orderToCreate.EffectiveDate = opp.CloseDate == null ? Date.today() : opp.CloseDate;
			orderToCreate.Status = 'Draft';
			if (opp.Pricebook2Id != null) {
				orderToCreate.Pricebook2Id = opp.Pricebook2Id;
			}

			ordersToInsert.add(orderToCreate);
			orderOpportunitySequence.add(opportunityId);
		}

		if (!ordersToInsert.isEmpty()) {
			Database.SaveResult[] dmlResults = Database.insert(ordersToInsert, false);
			for (Integer i = 0; i < dmlResults.size(); i++) {
				Id opportunityId = orderOpportunitySequence[i];
				Database.SaveResult saveResult = dmlResults[i];

				Result result = new Result();
				result.opportunityId = opportunityId;
				if (saveResult.isSuccess()) {
					result.orderId = saveResult.getId();
					result.success = true;
					result.message = 'Order created.';
					newOrderIdByOpportunityId.put(opportunityId, saveResult.getId());
				} else {
					result.success = false;
					result.message = saveResult.getErrors()[0].getMessage();
				}
				resultByOpportunityId.put(opportunityId, result);
			}
		}

		if (!newOrderIdByOpportunityId.isEmpty()) {
			cloneOpportunityDataToOrder(newOrderIdByOpportunityId, opportunitiesById, resultByOpportunityId);
		}

		List<Result> results = new List<Result>();
		List<Id> orderedOpportunityIds = new List<Id>(opportunityIds);
		orderedOpportunityIds.sort();
		for (Id opportunityId : orderedOpportunityIds) {
			if (resultByOpportunityId.containsKey(opportunityId)) {
				results.add(resultByOpportunityId.get(opportunityId));
			}
		}

		return results;
	}

	private static void cloneOpportunityDataToOrder(
		Map<Id, Id> orderIdByOpportunityId,
		Map<Id, Opportunity> opportunitiesById,
		Map<Id, Result> resultByOpportunityId
	) {
		Map<Id, Id> deliveryGroupIdMap = cloneOpportunityDeliveryGroups(orderIdByOpportunityId, resultByOpportunityId);
		createOrderItemsFromOpportunityLineItems(orderIdByOpportunityId, opportunitiesById, deliveryGroupIdMap, resultByOpportunityId);
	}

	private static void ensureOrderPricebooks(
		Map<Id, Id> orderIdByOpportunityId,
		Map<Id, Opportunity> opportunitiesById,
		Map<Id, Result> resultByOpportunityId
	) {
		if (orderIdByOpportunityId.isEmpty()) {
			return;
		}

		Map<Id, Order> ordersById = new Map<Id, Order>([
			SELECT Id, Pricebook2Id
			FROM Order
			WHERE Id IN :orderIdByOpportunityId.values()
		]);

		Id standardPricebookId = getStandardPricebookId();
		List<Order> ordersToUpdate = new List<Order>();
		List<Id> orderOpportunityIdsInOrder = new List<Id>();

		for (Id opportunityId : orderIdByOpportunityId.keySet()) {
			Order orderRecord = ordersById.get(orderIdByOpportunityId.get(opportunityId));
			if (orderRecord == null || orderRecord.Pricebook2Id != null) {
				continue;
			}

			Id pricebookId = opportunitiesById.containsKey(opportunityId)
				? opportunitiesById.get(opportunityId).Pricebook2Id
				: null;
			if (pricebookId == null) {
				pricebookId = standardPricebookId;
			}

			if (pricebookId == null) {
				appendResultMessage(
					resultByOpportunityId.get(opportunityId),
					'No active price book found to update the created order.'
				);
				continue;
			}

			ordersToUpdate.add(new Order(
				Id = orderRecord.Id,
				Pricebook2Id = pricebookId
			));
			orderOpportunityIdsInOrder.add(opportunityId);
		}

		if (ordersToUpdate.isEmpty()) {
			return;
		}

		Database.SaveResult[] updateResults = Database.update(ordersToUpdate, false);
		for (Integer i = 0; i < updateResults.size(); i++) {
			if (!updateResults[i].isSuccess()) {
				appendResultMessage(
					resultByOpportunityId.get(orderOpportunityIdsInOrder[i]),
					'Order price book update failed: ' + updateResults[i].getErrors()[0].getMessage()
				);
			}
		}
	}

	private static Map<Id, Id> cloneOpportunityDeliveryGroups(
		Map<Id, Id> orderIdByOpportunityId,
		Map<Id, Result> resultByOpportunityId
	) {
		Map<Id, Id> sourceToTargetDeliveryGroupId = new Map<Id, Id>();
		if (orderIdByOpportunityId.isEmpty()) {
			return sourceToTargetDeliveryGroupId;
		}

		List<DeliveryGroup__c> sourceGroups = [
			SELECT Id,
				RecordTypeId,
				Name,
				AddressLabel__c,
				DeliveryAddressHtml__c,
				PickupAddressHtml__c,
				DueDate__c,
				DeliveryType__c,
				DeliveryLocationType__c,
				PickupLocationType__c,
				DeliveryCenter__c,
				PickupCenter__c,
				Opportunity__c,
				Notes__c
			FROM DeliveryGroup__c
			WHERE Opportunity__c IN :orderIdByOpportunityId.keySet()
			ORDER BY CreatedDate ASC
		];

		if (sourceGroups.isEmpty()) {
			return sourceToTargetDeliveryGroupId;
		}

		Id orderDeliveryGroupRecordTypeId = getOrderDeliveryGroupRecordTypeId();
		List<DeliveryGroup__c> groupsToInsert = new List<DeliveryGroup__c>();
		List<Id> sourceGroupIdsInOrder = new List<Id>();
		List<Id> sourceOpportunityIdsInOrder = new List<Id>();

		for (DeliveryGroup__c sourceGroup : sourceGroups) {
			Id orderId = orderIdByOpportunityId.get(sourceGroup.Opportunity__c);
			if (orderId == null) {
				continue;
			}

			DeliveryGroup__c targetGroup = sourceGroup.clone(false, true, false, false);
			targetGroup.Opportunity__c = null;
			targetGroup.Order__c = orderId;
			if (orderDeliveryGroupRecordTypeId != null) {
				targetGroup.RecordTypeId = orderDeliveryGroupRecordTypeId;
			}

			groupsToInsert.add(targetGroup);
			sourceGroupIdsInOrder.add(sourceGroup.Id);
			sourceOpportunityIdsInOrder.add(sourceGroup.Opportunity__c);
		}

		if (groupsToInsert.isEmpty()) {
			return sourceToTargetDeliveryGroupId;
		}

		Database.SaveResult[] groupResults = Database.insert(groupsToInsert, false);
		for (Integer i = 0; i < groupResults.size(); i++) {
			Id sourceGroupId = sourceGroupIdsInOrder[i];
			Database.SaveResult saveResult = groupResults[i];

			if (saveResult.isSuccess()) {
				sourceToTargetDeliveryGroupId.put(sourceGroupId, saveResult.getId());
			} else {
				Id sourceOpportunityId = sourceOpportunityIdsInOrder[i];
				appendResultMessage(resultByOpportunityId.get(sourceOpportunityId),
					'Delivery group clone failed: ' + saveResult.getErrors()[0].getMessage());
			}
		}

		return sourceToTargetDeliveryGroupId;
	}

	private static void createOrderItemsFromOpportunityLineItems(
		Map<Id, Id> orderIdByOpportunityId,
		Map<Id, Opportunity> opportunitiesById,
		Map<Id, Id> deliveryGroupIdMap,
		Map<Id, Result> resultByOpportunityId
	) {
		if (orderIdByOpportunityId.isEmpty()) {
			return;
		}

		List<OpportunityLineItem> opportunityLineItems = [
			SELECT Id,
				OpportunityId,
				BasePrice__c,
				DeliveryType__c,
				Width__c,
				Height__c,
				Depth__c,
				Description,
				DiscountType__c,
				DiscountAmount__c,
				Notes__c,
				Quantity,
				UnitPrice,
				UnitType__c,
				WorkOrderStatus__c,
				DeliveryGroup__c,
				PricebookEntryId,
				Product2Id,
				ParentOrderProduct__c
			FROM OpportunityLineItem
			WHERE OpportunityId IN :orderIdByOpportunityId.keySet()
			ORDER BY CreatedDate ASC
		];

		if (opportunityLineItems.isEmpty()) {
			return;
		}

		Set<Id> opportunityIdsWithLineItems = new Set<Id>();
		for (OpportunityLineItem sourceItem : opportunityLineItems) {
			opportunityIdsWithLineItems.add(sourceItem.OpportunityId);
		}

		Map<Id, Id> lineItemOrderMap = new Map<Id, Id>();
		for (Id opportunityId : opportunityIdsWithLineItems) {
			if (orderIdByOpportunityId.containsKey(opportunityId)) {
				lineItemOrderMap.put(opportunityId, orderIdByOpportunityId.get(opportunityId));
			}
		}

		ensureOrderPricebooks(lineItemOrderMap, opportunitiesById, resultByOpportunityId);

		List<OrderItem> itemsToInsert = new List<OrderItem>();
		List<Id> sourceOliIdsInOrder = new List<Id>();
		List<Id> sourceOpportunityIdsInOrder = new List<Id>();
		Map<Id, Id> sourceParentBySourceOliId = new Map<Id, Id>();

		for (OpportunityLineItem sourceItem : opportunityLineItems) {
			Id orderId = orderIdByOpportunityId.get(sourceItem.OpportunityId);
			if (orderId == null) {
				continue;
			}

			OrderItem targetItem = new OrderItem();
			targetItem.OrderId = orderId;
			targetItem.PricebookEntryId = sourceItem.PricebookEntryId;
			targetItem.DeliveryGroup__c = deliveryGroupIdMap.get(sourceItem.DeliveryGroup__c);
			targetItem.BasePrice__c = sourceItem.BasePrice__c;
			targetItem.DeliveryType__c = sourceItem.DeliveryType__c;
			targetItem.Width__c = sourceItem.Width__c;
			targetItem.Height__c = sourceItem.Height__c;
			targetItem.Depth__c = sourceItem.Depth__c;
			targetItem.Description = sourceItem.Description;
			targetItem.DiscountType__c = sourceItem.DiscountType__c;
			targetItem.DiscountAmount__c = sourceItem.DiscountAmount__c;
			targetItem.Notes__c = sourceItem.Notes__c;
			targetItem.Quantity = sourceItem.Quantity == null ? 1 : sourceItem.Quantity;
			targetItem.UnitPrice = sourceItem.UnitPrice == null
				? (sourceItem.BasePrice__c == null ? 0.01 : sourceItem.BasePrice__c)
				: sourceItem.UnitPrice;
			targetItem.UnitType__c = sourceItem.UnitType__c;
			targetItem.WorkOrderStatus__c = sourceItem.WorkOrderStatus__c;

			itemsToInsert.add(targetItem);
			sourceOliIdsInOrder.add(sourceItem.Id);
			sourceOpportunityIdsInOrder.add(sourceItem.OpportunityId);
			sourceParentBySourceOliId.put(sourceItem.Id, sourceItem.ParentOrderProduct__c);
		}

		if (itemsToInsert.isEmpty()) {
			return;
		}

		Database.SaveResult[] insertResults = Database.insert(itemsToInsert, false);
		Map<Id, Id> orderItemIdBySourceOliId = new Map<Id, Id>();

		for (Integer i = 0; i < insertResults.size(); i++) {
			Id sourceOliId = sourceOliIdsInOrder[i];
			Database.SaveResult saveResult = insertResults[i];
			Id sourceOpportunityId = sourceOpportunityIdsInOrder[i];

			if (saveResult.isSuccess()) {
				orderItemIdBySourceOliId.put(sourceOliId, saveResult.getId());
			} else {
				appendResultMessage(
					resultByOpportunityId.get(sourceOpportunityId),
					'Order item clone failed: ' + saveResult.getErrors()[0].getMessage()
				);
			}
		}

		List<OrderItem> parentUpdates = new List<OrderItem>();
		List<Id> parentUpdateOpportunityIds = new List<Id>();
		for (Id sourceOliId : sourceOliIdsInOrder) {
			Id sourceParentOliId = sourceParentBySourceOliId.get(sourceOliId);
			Id createdOrderItemId = orderItemIdBySourceOliId.get(sourceOliId);
			Id createdParentOrderItemId = orderItemIdBySourceOliId.get(sourceParentOliId);

			if (createdOrderItemId != null && createdParentOrderItemId != null) {
				parentUpdates.add(new OrderItem(
					Id = createdOrderItemId,
					ParentOrderProduct__c = createdParentOrderItemId
				));
				parentUpdateOpportunityIds.add(sourceOpportunityIdsInOrder[sourceOliIdsInOrder.indexOf(sourceOliId)]);
			}
		}

		if (!parentUpdates.isEmpty()) {
			Database.SaveResult[] updateResults = Database.update(parentUpdates, false);
			for (Integer i = 0; i < updateResults.size(); i++) {
				if (!updateResults[i].isSuccess()) {
					appendResultMessage(
						resultByOpportunityId.get(parentUpdateOpportunityIds[i]),
						'Order item parent mapping failed: ' + updateResults[i].getErrors()[0].getMessage()
					);
				}
			}
		}
	}

	private static Id getOrderDeliveryGroupRecordTypeId() {
		Map<String, Schema.RecordTypeInfo> recordTypeByName =
			Schema.SObjectType.DeliveryGroup__c.getRecordTypeInfosByDeveloperName();

		if (recordTypeByName != null && recordTypeByName.containsKey('Order')) {
			return recordTypeByName.get('Order').getRecordTypeId();
		}

		return null;
	}

	private static Id getStandardPricebookId() {
		List<Pricebook2> standardPricebook = [
			SELECT Id
			FROM Pricebook2
			WHERE IsStandard = true
			AND IsActive = true
			LIMIT 1
		];

		return standardPricebook.isEmpty() ? null : standardPricebook[0].Id;
	}

	private static void appendResultMessage(Result result, String messageToAppend) {
		if (result == null || String.isBlank(messageToAppend)) {
			return;
		}

		if (String.isBlank(result.message)) {
			result.message = messageToAppend;
		} else {
			result.message += ' ' + messageToAppend;
		}
		result.success = false;
	}
}